/*-------------------------------------------------------------------*
 * Program      : msrpc_call_freepnp_1  (msrpc_call_freepn.c)                                         
 *
 * Language     : C
 *
 * Description  : This is the the MetDB freepn server. It is called by
 *              : the RPC server stub msrpc_call_freepn_1 (which was
 *              : generated by an rpcgen of msrpc_call_freepn.x. It
 *              : receives a structure from the client containing the
 *              : program number we wish to free.
 *
 * Called by    : msrpc_call_freepn_1  (msrpc_call_freepn_svc.c)
 *
 * Calls        : print_current_time   : print the current time
 *              : free_prognum         : free the program number
 *
 * Arguments    : struct *freepn_input (ip)  : program number, time
 *              : struct *freepn_output (op) : return status
 *
 * Changes      :
 *
 * 02-02-1998   : Written - S.Cox
 *
 * $Log:
 *  3    Met_DB_Project 1.2         08/01/2013 10:29:15    Sheila Needham  Stop
 *        log messages to file by nullifying the file connection.
 *  2    Met_DB_Project 1.1         06/10/2009 11:35:53    Sheila Needham
 *       z/os1.08 backup before change to z/os 1.10
 *  1    Met_DB_Project 1.0         11/10/2006 11:35:28    Kudsia Gwangwaa 
 * $
 * Revision 1.3  2001/01/09  16:45:03  16:45:03  usmdb (Generic MDB account)
 * Included local include file constants.h in order to
 * use DIAG_PATH_PREFIX. Increased length of variable
 * "outfile" - S.Cox
 * 
 * Revision 1.2  98/11/12  15:47:14  15:47:14  usmdb (Generic MDB account)
 * 16-11-98 S.Cox
 * Change code to write log output to /tmp/mdb instead of /tmp
 * 
 * Revision 1.1  98/02/03  10:00:26  10:00:26  usmdb (Generic MDB account)
 * Initial revision
 * 
 * $Source: /home/us0400/mdb/op/lib/RPC/server/broker/RCS/msrpc_call_freepn.c,v $
 *-------------------------------------------------------------------*/

#include <math.h>
#include <stdio.h>
#include <stdlib.h>
#include <stdarg.h>
#include <rpc/rpc.h>
#include "msrpc_call_freepn.h"
#include "constants.h"                                         /* 1.3 */

freepn_op_param *msrpc_call_freepnp_1(freepn_input)

freepn_ip_param *freepn_input;
{

/*--------------------------------------------------------------------*
 * Declare local variables.
 *--------------------------------------------------------------------*/

  FILE                   *svout;        /* diagnostic o/p file struct */
  char                   outfile[300];  /* diagnostic o/p filename v1.3 */
  char                   text[120];     /* line to write to outfile   */
  int                    status;

  static freepn_op_param freepn_output;

/*--------------------------------------------------------------------*
 * Open the output file for all C diagnostics. Write an error message
 * to stdout if this cannot be done.
 * Switch diagnostics off by setting svout to NULL
 *--------------------------------------------------------------------*/

 /* sprintf(outfile,"%s/mdbrpc_%d.txt",DIAG_PATH_PREFIX,
  freepn_input->TimeStamp);    /*

/*  svout = fopen(outfile, "a+"); */
  svout=NULL;
/*  if (svout == NULL) {
    (void)fprintf(stdout,"msrpc_call_freepnp_1: cannot open %s\n",
    outfile);
  } */

/*--------------------------------------------------------------------*
 * Output start of routine and current time to the diagnostics file.
 *--------------------------------------------------------------------*/

  sprintf(text,"\nmsrpc_call_freepnp_1: start of routine\n");
  (void)fputs(text,svout);

  print_current_time(svout);

/*--------------------------------------------------------------------*
 * Echo input arguments to the diagnostics file.
 *--------------------------------------------------------------------*/

  sprintf(text,"msrpc_call_freepnp_1: TimeStamp  = %d\n",
  freepn_input->TimeStamp);
  (void)fputs(text,svout);

  sprintf(text,"msrpc_call_freepnp_1: sv_prognum = %d\n",
  freepn_input->sv_prognum);
  (void)fputs(text,svout);

/*--------------------------------------------------------------------*
 * Call free_prognum to free the prognum.
 *--------------------------------------------------------------------*/

  status = free_prognum(freepn_input->sv_prognum, svout);

  freepn_output.status = status;

/*--------------------------------------------------------------------*
 * Output end of routine and current time to diagnostics file, close
 * diagnostics file and return to calling program.
 *--------------------------------------------------------------------*/

  print_current_time(svout);

  sprintf(text,"\nmsrpc_call_freepnp_1: end of routine, close svout\n");
  (void)fputs(text,svout);

  (void)fclose(svout);

  return(&freepn_output);
}
