/*--------------------------------------------------------------------*
 *
 * Program      : msrpc_call_brokerp_1  (msrpc_call_broker.c)
 *
 * Language     : C
 *
 * Description  : This is the the MetDB broker server. It is called by
 *              : the RPC server stub msrpc_call_broker_1 (which was
 *              : generated by an rpcgen of msrpc_call_broker.x. It
 *              : receives a structure from the client and returns a
 *              : structure (containing a program number). By this stage
 *              : mdb_rpc_broker will have started the main RPC server
 *
 * Called by    : msrpc_call_broker_1  (msrpc_call_broker_svc.c)
 *
 * Calls        : print_current_time   : print the current time
 *              : mdb_rpc_broker       : main broker routine
 *
 * Arguments    : struct *ClientDetails (ip)   :
 *              : struct *msrpc_BrokerOut (op) :
 *
 * $Revision: 3$
 * $Date: 08/01/2013 10:29:15$
 * $Source: /home/us0400/mdb/op/lib/RPC/server/broker/RCS/msrpc_call_broker.c,v $
 *
 * Changes      :
 *
 * $Log:
 *  3    Met_DB_Project 1.2         08/01/2013 10:29:15    Sheila Needham  Stop
 *        log messages to file by nullifying the file connection.
 *  2    Met_DB_Project 1.1         06/10/2009 11:35:53    Sheila Needham
 *       z/os1.08 backup before change to z/os 1.10
 *  1    Met_DB_Project 1.0         11/10/2006 11:35:26    Kudsia Gwangwaa 
 * $
 * Revision 1.3  2001/01/09  16:43:44  16:43:44  usmdb (Generic MDB account)
 * Included local include file constants.h in order to
 * use DIAG_PATH_PREFIX. Increased length of variable
 * "outfile" - S.Cox
 *
 * Revision 1.2  98/11/12  15:46:36  15:46:36  usmdb (Generic MDB account)
 * 16-11-98 S.Cox
 * Change code to write log file in /tmp/mdb instead of /tmp
 *
 * Revision 1.1  98/02/03  09:59:52  09:59:52  usmdb (Generic MDB account)
 * Initial revision
 *
 * 29-01-1998   : Written - S.Cox
 *--------------------------------------------------------------------*/

#include <stdio.h>
#include <time.h>
#include <rpc/rpc.h>
#include "msrpc_call_broker.h"
#include "constants.h"                                         /* 1.3 */

/*--------------------------------------------------------------------*
 * Function msrpc_call_brokerp_1
 *--------------------------------------------------------------------*/

msrpc_BrokerOut *msrpc_call_brokerp_1(ClientDetails)

msrpc_BrokerIn *ClientDetails;
{

/*--------------------------------------------------------------------*
 * Declare variables.
 *--------------------------------------------------------------------*/

  static msrpc_BrokerOut PortDetails;   /* output from function       */
  FILE                   *svout;        /* diagnostic o/p file struct */
  char                   outfile[300];  /* diagnostic o/p filename v1.3 */
  char                   text[120];     /* line to write to outfile   */

/*--------------------------------------------------------------------*
 * Open the output file for all C diagnostics.
 * Switch diagnostics off by setting svout to null.
 *--------------------------------------------------------------------*/

/*sprintf(outfile,"%s/mdbrpc_%d.txt",DIAG_PATH_PREFIX,
  ClientDetails->TimeStamp);                                          */

/*svout = fopen(outfile, "a+");   */
  svout = NULL;
/*  if (svout == NULL) {
    (void)fprintf(stdout,"msrpc_call_brokerp_1: cannot open %s\n",
    outfile);
  } */

/*--------------------------------------------------------------------*
 * Output function input details.
 *--------------------------------------------------------------------*/

  sprintf(text,"\nmsrpc_call_brokerp_1: start of routine\n");
  (void)fputs(text,svout);

  print_current_time(svout);

  sprintf(text,"msrpc_call_brokerp_1: TimeStamp = %d\n",
  ClientDetails->TimeStamp);
  (void)fputs(text,svout);

  sprintf(text,"msrpc_call_brokerp_1: wait      = %s\n",
  ClientDetails->wait);
  (void)fputs(text,svout);

  sprintf(text,"msrpc_call_brokerp_1: Branch    = %s\n",
  ClientDetails->Branch);
  (void)fputs(text,svout);

  sprintf(text,"msrpc_call_brokerp_1: UserId    = %s\n",
  ClientDetails->UserId);
  (void)fputs(text,svout);

  sprintf(text,"msrpc_call_brokerp_1: Tic       = %s\n",
  ClientDetails->Tic);
  (void)fputs(text,svout);

/*--------------------------------------------------------------------*
 * Get Program Number.
 *--------------------------------------------------------------------*/

  PortDetails.ProgNum = mdb_rpc_broker(svout);

  sprintf(text,"\nmsrpc_call_brokerp_1: Back from mdb_rpc_broker,\
  Prognum = %d\n",PortDetails.ProgNum);
  (void)fputs(text,svout);

/*--------------------------------------------------------------------*
 * Close diagnostics file & return to client.
 *--------------------------------------------------------------------*/

  print_current_time(svout);

  sprintf(text,"msrpc_call_brokerp_1: end of routine, close svout\n");
  (void)fputs(text,svout);

  (void)fclose(svout);

  return(&PortDetails);
}
