MODULE airidx_mod
  INTERFACE
    SUBROUTINE AIRIDX(TIMEYY,TIMETH,TIMEDD,TIMEHH,TIMEMM,REQ_YY,     &
                        REQ_MTH,REQ_DD,REQ_HH,MID_YY,MID_MTH,MID_DD, &
                        MID_HH,MID_MM,LAT,LONG,MID_LAT,MID_LONG,     &
                        SIGN,MATCH,NFT)
    IMPLICIT NONE

    ! Arguments

    INTEGER,INTENT(IN)    :: TIMEYY
    INTEGER,INTENT(IN)    :: TIMETH
    REAL,INTENT(IN)       :: TIMEDD
    REAL,INTENT(IN)       :: TIMEHH
    REAL,INTENT(IN)       :: TIMEMM
    INTEGER,INTENT(IN)    :: REQ_YY
    INTEGER,INTENT(IN)    :: REQ_MTH
    INTEGER,INTENT(IN)    :: REQ_DD
    INTEGER,INTENT(IN)    :: REQ_HH
    REAL,INTENT(INOUT)    :: MID_YY
    REAL,INTENT(INOUT)    :: MID_MTH
    REAL,INTENT(INOUT)    :: MID_DD
    REAL,INTENT(INOUT)    :: MID_HH
    REAL,INTENT(INOUT)    :: MID_MM
    REAL,INTENT(IN)       :: LAT
    REAL,INTENT(IN)       :: LONG
    REAL,INTENT(INOUT)    :: MID_LAT
    REAL,INTENT(INOUT)    :: MID_LONG
    CHARACTER(LEN=8),INTENT(IN) :: SIGN
    INTEGER,INTENT(IN)    :: NFT
    INTEGER,INTENT(OUT)   :: MATCH
    END SUBROUTINE AIRIDX
  END INTERFACE
END MODULE airidx_mod
