MODULE airloc_mod
 INTERFACE
  SUBROUTINE AIRLOC(REPLEN,REPORT,POINT,GRPLEN,LREPFL)
   INTEGER,INTENT(INOUT)         ::   POINT
   INTEGER,INTENT(OUT)           ::   GRPLEN
   INTEGER,INTENT(IN)            ::   REPLEN
   CHARACTER(LEN=*),INTENT(IN)   ::   REPORT
   LOGICAL,INTENT(OUT)           ::   LREPFL
  END SUBROUTINE AIRLOC
 END INTERFACE
END MODULE airloc_mod
