MODULE airsgn_mod
 INTERFACE
  SUBROUTINE AIRSGN(REPORT,REPLEN,POINT,SIGN)
   INTEGER,INTENT(INOUT)        :: POINT    ! Position in AIREP report
   INTEGER,INTENT(IN)           :: REPLEN   ! Report length
   CHARACTER(LEN=*),INTENT(IN)  :: REPORT
   CHARACTER(LEN=*),INTENT(OUT) :: SIGN      ! Aircraft call sign
  END SUBROUTINE AIRSGN
 END INTERFACE
END MODULE airsgn_mod
