MODULE airtmp_mod
 INTERFACE
  SUBROUTINE AIRTMP(REPLEN,REPORT,POINT,GRPLEN,CHARR,TEMP)
   INTEGER,INTENT(IN)              ::   REPLEN
   INTEGER,INTENT(INOUT)           ::   POINT
   INTEGER,INTENT(INOUT)           ::   GRPLEN
   CHARACTER(LEN=*),INTENT(IN)     ::   REPORT
   CHARACTER(LEN=20),INTENT(INOUT) ::   CHARR
   REAL,INTENT(OUT)                ::   TEMP
  END SUBROUTINE AIRTMP
 END INTERFACE
END MODULE airtmp_mod
