MODULE amdcor_mod
  INTERFACE
    SUBROUTINE AMDCOR(POINT,BEND,OAMD,AMDNUM,OCOR,CORNUM,BULL)

    IMPLICIT NONE

! Subroutine arguments:

    INTEGER,          INTENT(INOUT) :: POINT !A1
    INTEGER,          INTENT(INOUT) :: BEND !A2
    LOGICAL,          INTENT(OUT)   :: OAMD !A3
    CHARACTER(LEN=*), INTENT(OUT)   :: AMDNUM !A4
    LOGICAL,          INTENT(OUT)   :: OCOR !A5
    CHARACTER(LEN=*), INTENT(OUT)   :: CORNUM !A6
    CHARACTER(LEN=*), INTENT(INOUT) :: BULL !A7

    END SUBROUTINE AMDCOR
  END INTERFACE
END MODULE amdcor_mod
