MODULE arrindx_mod
  INTERFACE
    SUBROUTINE ARRINDX(IDESC,NELEM,IREPL,QCREQ,LFLAG,FIXARR,ELMNUM, &
                   SEGNUM,SUBNUM,NROWS,STYP,SEGST,SEGLEN, &
                   NSEGS,QCINC,NELREQ,DISPL,SOURCE,NEWSKLARR)   !A

    IMPLICIT NONE

! Subroutine arguments:

    INTEGER,      INTENT(IN)  ::  NELEM
    INTEGER,      INTENT(IN)  ::  IDESC(NELEM)
    INTEGER,      INTENT(IN)  ::  IREPL(NELEM)
    LOGICAL,      INTENT(IN)  ::  QCREQ
    LOGICAL,      INTENT(IN)  ::  LFLAG
    REAL,         INTENT(IN)  ::  FIXARR(:)
    INTEGER,      INTENT(IN)  ::  NROWS
    INTEGER,      INTENT(IN)  ::  ELMNUM(NROWS)
    INTEGER,      INTENT(IN)  ::  SEGNUM(NROWS)
    INTEGER,      INTENT(IN)  ::  SUBNUM(NROWS)
    INTEGER,      INTENT(IN)  ::  NSEGS
    INTEGER,      INTENT(IN)  ::  STYP(NSEGS)
    INTEGER,      INTENT(IN)  ::  SEGST(NSEGS)
    INTEGER,      INTENT(IN)  ::  SEGLEN(NSEGS)
    INTEGER,      INTENT(IN)  ::  QCINC
    INTEGER,      INTENT(OUT) ::  NELREQ
    INTEGER,      INTENT(OUT) ::  DISPL(:)
    INTEGER,      INTENT(OUT) ::  SOURCE(:)
    LOGICAL,      INTENT(IN)  ::  NEWSKLARR !- TRUE if New MDB call (ISTAT=0) !A

    END SUBROUTINE ARRINDX
  END INTERFACE
END MODULE arrindx_mod
