MODULE artmck_mod
  INTERFACE
    LOGICAL FUNCTION ARTMCK(DATIME,SYS_YEAR)

    IMPLICIT NONE

    ! Arguments

    INTEGER,INTENT(IN)  :: DATIME(5)
    INTEGER,INTENT(IN)  :: SYS_YEAR
    END FUNCTION ARTMCK
  END INTERFACE
END MODULE artmck_mod
