MODULE asc2eb_mod
  INTERFACE
    SUBROUTINE ASC2EB(LENGTH,STRING)
      IMPLICIT NONE
      INTEGER :: LENGTH
      CHARACTER(LEN=LENGTH) :: STRING
    END SUBROUTINE ASC2EB
  END INTERFACE
END MODULE asc2eb_mod
