MODULE BATCHLOG_MOD
 INTERFACE
  SUBROUTINE BATCHLOG(UID,DATA_TYPE,DATE)
   IMPLICIT NONE
   CHARACTER(5),INTENT(IN)     ::   UID
   CHARACTER(8),INTENT(IN)     ::   DATA_TYPE
   INTEGER,INTENT(IN)          ::   DATE(8)
  END SUBROUTINE BATCHLOG
 END INTERFACE
END MODULE BATCHLOG_MOD
