MODULE bathy_mod
 INTERFACE
  SUBROUTINE BATHY(REPORT,TTAAII,CCCC,OCOR,NFT)
   CHARACTER(LEN=*),INTENT(IN)  ::    REPORT
   CHARACTER(LEN=*),INTENT(IN)  ::    TTAAII
   CHARACTER(LEN=4),INTENT(IN)  ::    CCCC
   INTEGER,INTENT(IN)           ::    NFT
   LOGICAL,INTENT(IN)           ::    OCOR
  END SUBROUTINE BATHY
 END INTERFACE
END MODULE bathy_mod
