MODULE becpos_mod
 INTERFACE
  SUBROUTINE BECPOS (BEAC_REQ, BLAT, BLONG, NFTBCN, ISTAT)
   CHARACTER(LEN=*),INTENT(IN)   ::  BEAC_REQ ! ID. OF REQUIRED BEACON
   REAL,INTENT(OUT)              ::  BLAT     ! REQ LAT & LONG
   REAL,INTENT(OUT)              ::  BLONG    ! REQUIRED LAT & LONG
   INTEGER,INTENT(IN)            ::  NFTBCN   ! UNIT NO FOR BEACON LIST
   INTEGER,INTENT(OUT)           ::  ISTAT    ! RETURN CODE
  END SUBROUTINE BECPOS
 END INTERFACE
END MODULE becpos_mod
