MODULE bthind_mod
 INTERFACE
  SUBROUTINE BTHIND(EXPARR,IDFLAG,ID,OCOR,ENTRY)
   CHARACTER(LEN=9),INTENT(IN)     ::     ID
   CHARACTER(LEN=23),INTENT(OUT)   ::     ENTRY
   REAL,INTENT(IN)                 ::     EXPARR(0:1000)
   LOGICAL,INTENT(IN)              ::     OCOR
   LOGICAL,INTENT(IN)              ::     IDFLAG
  END SUBROUTINE BTHIND
 END INTERFACE
END MODULE bthind_mod
