 MODULE bthsc4_mod
  INTERFACE
   SUBROUTINE BTHSC4(REPORT,REPLEN,EXPARR,IDFLG,ID)
    CHARACTER(LEN=*), INTENT(IN)     ::   REPORT
    CHARACTER(LEN=9), INTENT(OUT)    ::   ID
    REAL,             INTENT(INOUT)  ::   EXPARR(0:)
    INTEGER,          INTENT(INOUT)  ::   REPLEN
    LOGICAL,          INTENT(OUT)    ::   IDFLG
   END SUBROUTINE BTHSC4
  END INTERFACE
 END MODULE bthsc4_mod
