  MODULE bthsc3_mod
   INTERFACE
    SUBROUTINE BTHSC3(REPORT,REPLEN,EXPARR,TOTDEP,POS,POS1A)
     CHARACTER(LEN=*), INTENT(IN)     ::  REPORT
     REAL,             INTENT(INOUT)  ::  EXPARR(0:)
     REAL,             INTENT(INOUT)  ::  TOTDEP
     INTEGER,          INTENT(IN)     ::  REPLEN
     INTEGER,          INTENT(INOUT)  ::  POS
     INTEGER,          INTENT(OUT)    ::  POS1A
    END SUBROUTINE BTHSC3
   END INTERFACE
  END MODULE bthsc3_mod
