MODULE bthsc2_mod
 INTERFACE
  SUBROUTINE BTHSC2(REPORT,REPLEN,EXPARR,TOTDEP,POS,POS1A)
   CHARACTER(LEN=*), INTENT(IN)     ::   REPORT
   REAL,             INTENT(INOUT)  ::   EXPARR(0:)
   REAL,             INTENT(OUT)    ::   TOTDEP
   INTEGER,          INTENT(IN)     ::   REPLEN
   INTEGER,          INTENT(INOUT)  ::   POS
   INTEGER,          INTENT(OUT)    ::   POS1A
  END SUBROUTINE BTHSC2
 END INTERFACE
END MODULE bthsc2_mod
