MODULE bthsc1_mod
 INTERFACE
  SUBROUTINE BTHSC1 (REPORT, REPLEN, EXPARR, POS, DATIME, MIMJ, IERR)
   CHARACTER(LEN=*), INTENT(IN)     ::  REPORT
   CHARACTER(LEN=4), INTENT(IN)     ::  MIMJ
   REAL,             INTENT(INOUT)  ::  EXPARR(0:)
   INTEGER,          INTENT(IN)     ::  REPLEN
   INTEGER,          INTENT(INOUT)  ::  POS
   INTEGER,          INTENT(OUT)    ::  IERR
   INTEGER,          INTENT(OUT)    ::  DATIME(5)
  END SUBROUTINE BTHSC1
 END INTERFACE
END MODULE bthsc1_mod
