MODULE BUFDRPL_mod
  INTERFACE
    SUBROUTINE BUFDRPL(STRING,NOBS,CMPRES,MAXDES,MAXVAL,IBEFOR, &
     &VALUES,IVAL,DESCR,N,ND,NTIMES,IVER,IRC)
      IMPLICIT NONE
      CHARACTER(LEN=*) :: STRING
      INTEGER :: NOBS
      LOGICAL :: CMPRES
      INTEGER :: MAXDES
      INTEGER :: MAXVAL
      INTEGER :: IBEFOR
      REAL :: VALUES(*)
      INTEGER :: IVAL
      INTEGER :: DESCR(*)
      INTEGER :: N
      INTEGER :: ND
      INTEGER :: NTIMES
      INTEGER :: IVER
      INTEGER :: IRC
    END SUBROUTINE BUFDRPL
  END INTERFACE
END MODULE BUFDRPL_mod
