MODULE BUFDSPL_mod
  INTERFACE
    SUBROUTINE BUFDSPL(NAME,UNITS,IFORMAT,SCALE,WIDTH,NOBS,IVAL,&
     &NCREM,VALUES,DESCR)
      IMPLICIT NONE
      CHARACTER(LEN=54) :: NAME
      CHARACTER(LEN=12) :: UNITS
      CHARACTER(LEN=1) :: IFORMAT
      INTEGER :: SCALE
      INTEGER :: WIDTH
      INTEGER :: NOBS
      INTEGER :: IVAL
      INTEGER :: NCREM
      REAL :: VALUES(*)
      INTEGER :: DESCR
    END SUBROUTINE BUFDSPL
  END INTERFACE
END MODULE BUFDSPL_mod
