MODULE BUFDATA_mod
  INTERFACE
    SUBROUTINE BUFDATA(DESCR,VALUES,NAMES,ND,NOBS,STRING,CMPRES,&
      & DSPLAY,MAXDES,MAXVAL,IVER,IRC)
      IMPLICIT NONE
      INTEGER :: DESCR(*)
      REAL :: VALUES(*)
      CHARACTER(LEN=*) :: NAMES
      INTEGER :: ND
      INTEGER :: NOBS
      CHARACTER(LEN=*) :: STRING
      LOGICAL :: CMPRES
      LOGICAL :: DSPLAY
      INTEGER :: MAXDES
      INTEGER :: MAXVAL
      INTEGER :: IVER
      INTEGER :: IRC
    END SUBROUTINE BUFDATA
  END INTERFACE
END MODULE BUFDATA_mod
