MODULE BUFDELT_mod
  INTERFACE
    SUBROUTINE BUFDELT(NDTOTAL,ND,DESCR)
      IMPLICIT NONE
      INTEGER :: NDTOTAL
      INTEGER :: ND
      INTEGER :: DESCR(*)
    END SUBROUTINE BUFDELT
  END INTERFACE
END MODULE BUFDELT_mod
