MODULE bufdass_mod
  INTERFACE
    SUBROUTINE BUFDASS(STRING,NOBS,CMPRES,NASSOX,MASSOC,LASSOC, &
      &  DSPLAY,IBEFOR,VALUES,IVAL,DESCR,N,ND)
      IMPLICIT NONE
      CHARACTER(LEN=*) :: STRING
      INTEGER :: NOBS
      LOGICAL :: CMPRES
      INTEGER :: NASSOX
      INTEGER :: MASSOC(:)
      INTEGER :: LASSOC(:)
      LOGICAL :: DSPLAY
      INTEGER :: IBEFOR
      REAL :: VALUES(*)
      INTEGER :: IVAL
      INTEGER :: DESCR(*)
      INTEGER :: N
      INTEGER :: ND
    END SUBROUTINE BUFDASS
  END INTERFACE
END MODULE bufdass_mod
