MODULE bufd203_mod
  INTERFACE
    SUBROUTINE BUFD203(Y,STRING,DESCR,CMPRES,IBEFOR,N,NREF,     &
     &REFDES,NEWREF,IRC)
      IMPLICIT NONE
      INTEGER :: Y
      CHARACTER(LEN=*) :: STRING
      INTEGER :: DESCR(*)
      LOGICAL :: CMPRES
      INTEGER :: IBEFOR
      INTEGER :: N
      INTEGER :: NREF
      INTEGER :: REFDES(:)
      INTEGER :: NEWREF(:)
      INTEGER :: IRC
    END SUBROUTINE BUFD203
  END INTERFACE
END MODULE bufd203_mod
