MODULE BUFINDX_MOD
INTERFACE
SUBROUTINE BUFINDX(CINDEX,IREF,NREF,IREPL,QCREQ,IFAIL,LFLAG, &
     &           LOCALD,MESSAGE,NELREQ,DISPL,SOURCE,VALUES,  &
     &           MDATA,CNAME,IEXTRA,NREP,MXSIZE,NEWMDBCALL,  &
     &           MEXT)

  INTEGER,INTENT(IN)             :: MEXT
  INTEGER,INTENT(IN)             :: NREF
  INTEGER,INTENT(IN)             :: IREF(NREF)
  INTEGER,INTENT(IN)             :: IREPL(NREF)
  INTEGER,INTENT(OUT)            :: IFAIL
  INTEGER,INTENT(OUT)            :: NELREQ
  INTEGER,INTENT(IN)             :: MXSIZE
  INTEGER,INTENT(IN)             :: MDATA
  INTEGER,INTENT(OUT)            :: IEXTRA(MEXT)
  INTEGER,INTENT(OUT)            :: NREP
  INTEGER,INTENT(OUT)            :: DISPL(MXSIZE)
  INTEGER,INTENT(OUT)            :: SOURCE(MXSIZE)
  REAL,INTENT(OUT)               :: VALUES(MDATA)
  LOGICAL,INTENT(IN)            :: QCREQ
  LOGICAL,INTENT(IN)             :: LFLAG
  LOGICAL,INTENT(INOUT)          :: NEWMDBCALL
  CHARACTER(LEN=*),INTENT(INOUT) :: CNAME
  CHARACTER(LEN=*),INTENT(IN)    :: CINDEX(:)
  CHARACTER(LEN=6),INTENT(IN)    :: LOCALD
  CHARACTER(LEN=*),INTENT(IN)    :: MESSAGE
END SUBROUTINE BUFINDX
END INTERFACE
END MODULE BUFINDX_mod
