MODULE BUFRQEL_mod
  INTERFACE
    SUBROUTINE BUFRQEL(STRING,CMPRES,LASTEL,LASBIT,N,NEXBIT,    &
     &SCALE,WIDTH,REFVAL,FORMAT,DESCR,NLOG,IRC)
      IMPLICIT NONE
      CHARACTER(LEN=*), INTENT(IN)     :: STRING
      LOGICAL,          INTENT(IN)     :: CMPRES
      INTEGER,          INTENT(IN)     :: LASTEL
      INTEGER,          INTENT(IN)     :: LASBIT
      INTEGER,          INTENT(IN)     :: N
      INTEGER,          INTENT(INOUT)  :: NEXBIT
      INTEGER,          INTENT(INOUT)  :: SCALE
      INTEGER,          INTENT(INOUT)  :: WIDTH
      INTEGER,          INTENT(INOUT)  :: REFVAL
      CHARACTER(LEN=1), INTENT(INOUT)  :: FORMAT
      INTEGER,          INTENT(INOUT)  :: DESCR(*)
      INTEGER,          INTENT(INOUT)  :: NLOG
      INTEGER,          INTENT(OUT)    :: IRC
    END SUBROUTINE BUFRQEL
  END INTERFACE
END MODULE BUFRQEL_mod
