MODULE BUFR207_mod
  INTERFACE
    SUBROUTINE BUFR207(Y,SCALE,WIDTH,REFVAL)
      IMPLICIT NONE
      INTEGER :: Y
      INTEGER :: SCALE
      INTEGER :: WIDTH
      INTEGER :: REFVAL
    END SUBROUTINE BUFR207
  END INTERFACE
END MODULE BUFR207_mod
