MODULE BUFRSEQ_mod
  INTERFACE
    SUBROUTINE BUFRSEQ(X,Y,MAXDES,N,ND,DESCR,IRC)
      IMPLICIT NONE
      INTEGER :: X
      INTEGER :: Y
      INTEGER :: MAXDES
      INTEGER :: N
      INTEGER :: ND
      INTEGER :: DESCR(*)
      INTEGER :: IRC
    END SUBROUTINE BUFRSEQ
  END INTERFACE
END MODULE BUFRSEQ_mod
