MODULE bufrpath_mod
 INTERFACE
  SUBROUTINE BUFRPATH(DIR_NAME,LEN_DIR_NAME)
   CHARACTER(LEN=*)  ::  DIR_NAME   
   INTEGER ::   LEN_DIR_NAME   
  END SUBROUTINE BUFRPATH
 END INTERFACE
END MODULE bufrpath_mod
