MODULE bufval_mod
  INTERFACE
      SUBROUTINE BUFVAL(VALUE,SCALE,REFVAL,WIDTH,X,IVALUE)
      REAL      VALUE
      INTEGER   SCALE
      INTEGER   REFVAL
      INTEGER   WIDTH
      INTEGER   X
      INTEGER   IVALUE
      END SUBROUTINE BUFVAL
  END INTERFACE
END MODULE bufval_mod
