MODULE bulhed_mod
  INTERFACE
    SUBROUTINE BULHED(POINT,BULEND,TTAAII,CCCC,YYGGGG, &
                      OAMD,AMDNUM,OCOR,CORNUM,BULL)
      IMPLICIT NONE
      INTEGER, INTENT(OUT)                  :: POINT      ! POINTER TO WHERE TO START IN BULLETIN
      INTEGER, INTENT(OUT)                  :: BULEND     ! NUMBER OF LAST CHARACTER IN BULLETIN
      CHARACTER(LEN=*), INTENT(OUT)         :: TTAAII     ! TT TYPE OF BULLETIN
      CHARACTER(LEN=*), INTENT(OUT)         :: CCCC       ! ORIGINATING CENTRE FOR BULLETIN
      CHARACTER(LEN=*), INTENT(OUT)         :: YYGGGG     ! TIME OF BULLETIN
      LOGICAL, INTENT(OUT)                  :: OAMD       ! SET IF BULLETIN AMENDED
      CHARACTER(LEN=*), INTENT(OUT)         :: AMDNUM     ! NUMBER OF BULLETIN AMENDMENT
      LOGICAL, INTENT(OUT)                  :: OCOR       ! SET IF BULLETIN CORRECTED
      CHARACTER(LEN=*), INTENT(OUT)         :: CORNUM     ! NUMBER OF BULLETIN CORRECTION
      CHARACTER(LEN=*), INTENT(INOUT)       :: BULL       ! REPORT DATA
    END SUBROUTINE BULHED
  END INTERFACE
END MODULE bulhed_mod
