MODULE bulled_mod
  INTERFACE
    SUBROUTINE BULLED(ISTART,IEND,BULL)

    IMPLICIT NONE

! Subroutine arguments:

    INTEGER,          INTENT(IN)    :: ISTART !a1
    INTEGER,          INTENT(INOUT) :: IEND !a2
    CHARACTER(LEN=*), INTENT(INOUT) :: BULL !a3

    END SUBROUTINE BULLED
  END INTERFACE
END MODULE bulled_mod
