MODULE century_mod
  INTERFACE
    FUNCTION CENTURY (TWOFIG_YEAR)

    IMPLICIT NONE

    INTEGER,INTENT(IN) ::  TWOFIG_YEAR  ! AS SUPPLIED BY USER ROUTINE..
    INTEGER            ::  CENTURY      !

    END FUNCTION CENTURY
  END INTERFACE
END MODULE century_mod
