MODULE clmbul_mod
  INTERFACE
    SUBROUTINE CLMBUL(POINT,BEND,TTAAII,CCCC,OCOR,NFT,BULL) 
      IMPLICIT NONE
      INTEGER, INTENT(INOUT)          :: POINT  ! to next group (group after CLIMAT?)
      INTEGER, INTENT(INOUT)          :: BEND   ! POSN OF LAST CHARACTER IN BULLETIN
      CHARACTER(LEN=*), INTENT(IN)    :: TTAAII ! TYPE OF BULLETIN  
      CHARACTER(LEN=*), INTENT(IN)    :: CCCC   ! ORIGINATING CENTRE FOR BULLETIN
      LOGICAL, INTENT(IN)             :: OCOR   ! TRUE IF BULLETIN CORRECTED
      INTEGER, INTENT(IN)             :: NFT    ! FT NUMBER FOR CLIMAT STORAGE
      CHARACTER(LEN=*), INTENT(INOUT) :: BULL   ! bulletin 
    END SUBROUTINE CLMBUL
  END INTERFACE
END MODULE clmbul_mod
