MODULE CODE_mod
  INTERFACE
    SUBROUTINE CODE(DESCR,FIGURE,WORDS)
      IMPLICIT NONE
      INTEGER :: DESCR
      INTEGER :: FIGURE
      CHARACTER(LEN=*) :: WORDS
    END SUBROUTINE CODE
  END INTERFACE
END MODULE CODE_mod
