MODULE CONDES_MOD
  INTERFACE
    SUBROUTINE CONDES(IDESC,NDES,IDISP)
    
      IMPLICIT NONE
    
      ! Argument declarations
      INTEGER, INTENT(IN)      :: NDES         ! NUMBER OF ELEMENTS
      INTEGER, INTENT(INOUT)   :: IDESC(NDES)  ! LIST OF ELEMENT NUMNERS
      INTEGER, INTENT(INOUT)   :: IDISP(NDES)  ! LIST DISPLACEMENTS
    
    END SUBROUTINE CONDES
  END INTERFACE
END MODULE CONDES_MOD
