MODULE DEBUFR_mod
  INTERFACE
    SUBROUTINE DEBUFR(DESCR,VALUES,NAMES,ND,NOBS,STRING,DSPLAY)
      IMPLICIT NONE
      INTEGER :: DESCR(*)
      REAL :: VALUES(*)
      CHARACTER(LEN=*) :: NAMES
      INTEGER :: ND
      INTEGER :: NOBS
      CHARACTER(LEN=*) :: STRING
      LOGICAL :: DSPLAY
    END SUBROUTINE DEBUFR
  END INTERFACE
END MODULE DEBUFR_mod
