MODULE DESFXY_mod
  INTERFACE
    SUBROUTINE DESFXY(DESCR,F,X,Y)
      IMPLICIT NONE
      INTEGER  :: DESCR
      INTEGER  :: F
      INTEGER :: X
      INTEGER :: Y
    END SUBROUTINE DESFXY
  END INTERFACE
END MODULE DESFXY_mod
