MODULE dreg_mod
 INTERFACE
  SUBROUTINE DREG(NUMERR,TEXT,BULL,CALLER,TYPE,HEADER,NTMSG,DSN)
   INTEGER,         INTENT(IN)    ::  NUMERR   ! (1)ERROR CODE NUMBER
   CHARACTER(LEN=*),INTENT(IN)    ::  TEXT     ! (2)
   CHARACTER(LEN=*),INTENT(IN)    ::  BULL     ! (3) VARIABLE LENGTH STRINGS
   CHARACTER(LEN=*),INTENT(IN)    ::  CALLER   ! (4)
   CHARACTER(LEN=*),INTENT(IN)    ::  TYPE     ! (5)
   CHARACTER(LEN=*),INTENT(IN)    ::  HEADER   ! (6)
   INTEGER,         INTENT(IN)    ::  NTMSG(8) ! (7) TIME OF MESS (AS FROM "DATIM")
   CHARACTER(LEN=*),INTENT(IN)    ::  DSN      ! (8)
  END SUBROUTINE DREG
 END INTERFACE
END MODULE dreg_mod
