MODULE DSINFO_MOD
  INTERFACE
    SUBROUTINE DSINFO (TYPENAME, IOPEN, IUNIT, LENREC, KODE, DSN)
      ! Interface Arguments
      CHARACTER (LEN=*),INTENT(IN)   :: TYPENAME  ! (A1) DATA SET TYPE REQUIRED
      INTEGER, INTENT(IN)            :: IOPEN     ! (A2) DATA SET ACCESS REQUIRED
      INTEGER, INTENT(INOUT)         :: IUNIT     ! (A3) DATA SET UNIT NUMBER (RETURNED)
      INTEGER, INTENT(OUT)           :: LENREC    ! (A4) DATA SET RECORD LENGTH (RETURNED)
      INTEGER, INTENT(OUT)           :: KODE      ! (A5) RETURN CODE (SEE ABOVE)
      CHARACTER(LEN=44), INTENT(OUT) :: DSN       ! (A6) DATA SET NAME
    END SUBROUTINE DSINFO
  END INTERFACE
END MODULE DSINFO_MOD