MODULE dsopen_mod
  INTERFACE
    SUBROUTINE DSOPEN (IUNIT, DDNAME, DIRECT, FORMAT, LENREC, IOPEN, &
                                                              IOFLAG)

    IMPLICIT NONE

    INTEGER, INTENT(IN)            :: IUNIT    ! UNIT NUMBER FOR DATA SET
    CHARACTER (LEN=*), INTENT(IN)  :: DDNAME   ! DDNAME FOR STORAGE DATA SET
    LOGICAL, INTENT(IN)            :: DIRECT   ! FLAG FOR DIRECT/SEQUENTIAL ACCESS
    LOGICAL, INTENT(IN)            :: FORMAT   ! FLAG FOR FORMATTED/UNFORMATTED DATA
    INTEGER, INTENT(IN)            :: LENREC   ! RECORD LENGTH OF DATA SET
    INTEGER, INTENT(IN)            :: IOPEN    ! "OPEN" ACTION (1=READ, 2=WRITE, 3=BOTH)
    INTEGER, INTENT(OUT)           :: IOFLAG   ! STATUS FLAG FROM "OPEN" STATEMENT

    END SUBROUTINE DSOPEN
  END INTERFACE
END MODULE dsopen_mod
