MODULE DT2HRS_MOD
  INTERFACE
    INTEGER FUNCTION DT2HRS(IY,IM,ID,IH)

    ! ARGUMENT DECLARATIONS
    INTEGER, INTENT(IN)  :: IY    ! YEAR
    INTEGER, INTENT(IN)  :: IM    ! MONTH
    INTEGER, INTENT(IN)  :: ID    ! DAY
    INTEGER, INTENT(IN)  :: IH    ! HOUR

    END FUNCTION DT2HRS
  END INTERFACE
END MODULE DT2HRS_MOD
