MODULE eb2asc_mod
  INTERFACE
    SUBROUTINE EB2ASC(LENGTH,STRING)

    IMPLICIT NONE

    INTEGER, INTENT(IN)                   :: LENGTH
    CHARACTER(LEN=LENGTH), INTENT(INOUT)  :: STRING

    END SUBROUTINE EB2ASC
  END INTERFACE
END MODULE eb2asc_mod
