MODULE ebcdic_mod
 INTERFACE
  SUBROUTINE EBCDIC (LEN, STRING)
   INTEGER,INTENT(IN)               ::     LEN
   CHARACTER(LEN=LEN),INTENT(INOUT) ::  STRING
  END SUBROUTINE EBCDIC
 END INTERFACE
END MODULE ebcdic_mod
