MODULE enbufr_mod
  INTERFACE
    SUBROUTINE ENBUFR(DESCR,VALUES,ND,NELEM,NOBS,NAMES,DATIME,  &
      MESAGE,CMPRES,L,IVER)
      IMPLICIT NONE
      INTEGER :: NOBS
      INTEGER :: NELEM
      INTEGER :: DESCR(*)
      REAL :: VALUES(NOBS,NELEM)
      INTEGER :: ND
      CHARACTER(LEN=*) :: NAMES
      INTEGER :: DATIME(5)
      CHARACTER(LEN=*) :: MESAGE
      LOGICAL :: CMPRES
      INTEGER :: L
      INTEGER :: IVER
    END SUBROUTINE ENBUFR
  END INTERFACE
END MODULE enbufr_mod
