MODULE enbufv2_mod
  INTERFACE
    SUBROUTINE ENBUFV2(DESCR,VALUES,ND,NELEM,NOBS,NAMES,DATIME, &
     &MESAGE,CMPRES,L,EDITION,MASTERTABLE,ORIGCENTRE,DATATYPE, &
     &DATASUBTYPE,VERMASTAB,VERLOCTAB,EXTRASECT1,CHARSECT1,EXTRASECT2, &
     &CHARSECT2,SECT3TYPE)
      IMPLICIT NONE
      INTEGER :: NOBS
      INTEGER :: NELEM
      INTEGER :: DESCR(:)
      REAL :: VALUES(NOBS,NELEM)
      INTEGER :: ND
      CHARACTER(LEN=*) :: NAMES
      INTEGER :: DATIME(5)
      CHARACTER(LEN=*) :: MESAGE
      LOGICAL :: CMPRES
      INTEGER :: L
      INTEGER :: EDITION
      INTEGER :: MASTERTABLE
      INTEGER :: ORIGCENTRE
      INTEGER :: DATATYPE
      INTEGER :: DATASUBTYPE
      INTEGER :: VERMASTAB
      INTEGER :: VERLOCTAB
      LOGICAL :: EXTRASECT1
      CHARACTER(LEN=*) :: CHARSECT1
      LOGICAL :: EXTRASECT2
      CHARACTER(LEN=*) :: CHARSECT2
      INTEGER :: SECT3TYPE
    END SUBROUTINE ENBUFV2
  END INTERFACE
END MODULE enbufv2_mod
