MODULE encode_mod
  INTERFACE
    SUBROUTINE ENCODE(DESCR,VALUES,ND,NELEM,NOBS,NAMES,STRING,  &
      CMPRES,L4,IVER)
      IMPLICIT NONE
      INTEGER :: NOBS
      INTEGER :: NELEM
      INTEGER :: DESCR(*)
      REAL :: VALUES(NOBS,NELEM)
      INTEGER :: ND
      CHARACTER(LEN=*) :: NAMES
      CHARACTER(LEN=*) :: STRING
      LOGICAL :: CMPRES
      INTEGER :: L4
      INTEGER :: IVER
    END SUBROUTINE ENCODE
  END INTERFACE
END MODULE encode_mod
