MODULE eochn_mod
  INTERFACE
    LOGICAL FUNCTION EOCHN(IPT,IMAX,INC)
    IMPLICIT NONE
    INTEGER,      INTENT(IN) ::  IPT
    INTEGER,      INTENT(IN) ::  IMAX
    INTEGER,      INTENT(IN) ::  INC

    END FUNCTION EOCHN
  END INTERFACE
END MODULE eochn_mod
