MODULE EXPELM_MOD
  INTERFACE
    SUBROUTINE EXPELM(REQ,IPOS,ILEN,USRELM,NUM,QCFLAG,IFAIL,CERR)

      IMPLICIT NONE

      ! ARGUMENTS IN ORDER (SEE ABOVE)
      CHARACTER(LEN=*), INTENT(IN)   :: REQ       ! METDB REQUEST STRING
      INTEGER, INTENT(INOUT)         :: IPOS      ! POINTER TO FIRST ELE
      INTEGER, INTENT(IN)            :: ILEN      ! LENGTH OF REQUEST ST
      CHARACTER(LEN=36), INTENT(INOUT) :: USRELM(:) ! ARRAY OF FULLY QUALI
      INTEGER, INTENT(OUT)           :: NUM       ! NUMBER OF ELEMENTS O
      LOGICAL, INTENT(OUT)           :: QCFLAG    ! TRUE IF LAST EL +QC_
      INTEGER, INTENT(OUT)           :: IFAIL     ! ERROR CODE 8 - FATAL
      CHARACTER(LEN=*), INTENT(OUT)  :: CERR      ! ERROR MESSAGE

    END SUBROUTINE EXPELM
  END INTERFACE
END MODULE EXPELM_MOD
