MODULE EXPREQ_MOD
  INTERFACE
    LOGICAL FUNCTION EXPREQ(IDESC,NDES)

      IMPLICIT NONE

      ! ARGUMENT DECLARATIONS
      INTEGER, INTENT(IN)       :: NDES              !
      INTEGER, INTENT(IN)       :: IDESC(NDES)       ! USER'S ELEMENT AR

    END FUNCTION EXPREQ
  END INTERFACE
END MODULE
