MODULE FFUNIT_mod
  INTERFACE
    SUBROUTINE FFUNIT(WMOBLK,WMOSTN,IW)

    IMPLICIT NONE

    INTEGER, INTENT(IN)   :: WMOBLK      ! (A1)
    INTEGER, INTENT(IN)   :: WMOSTN      ! (A2)
    INTEGER, INTENT(OUT)  :: IW          ! (A3)

    END SUBROUTINE FFUNIT
  END INTERFACE
END MODULE FFUNIT_mod
