MODULE findpath_mod
  INTERFACE
    FUNCTION FINDPATH(PREFIX, PATH, PREF, NPATH)

    CHARACTER(*),INTENT(IN):: PREFIX
    INTEGER     ,INTENT(IN):: NPATH
    CHARACTER(*),INTENT(IN):: PATH(NPATH)
    CHARACTER(*),INTENT(IN):: PREF(NPATH)

    CHARACTER(LEN=LEN(PATH(1))) :: FINDPATH

    END FUNCTION FINDPATH
  END INTERFACE
END MODULE findpath_mod
