MODULE findrec_mod
  INTERFACE
    SUBROUTINE FINDREC (RECORD, NEXTDS)

    IMPLICIT NONE

! Subroutine arguments:

    CHARACTER(LEN=*), INTENT(INOUT) :: RECORD(*) !a01 HOUSEKEEPING DATASET RECORDS
    INTEGER,          INTENT(OUT)   :: NEXTDS    !a02 NUMBER OF SLOT FOR NEXT DATA SET

    END SUBROUTINE FINDREC
  END INTERFACE
END MODULE findrec_mod
