MODULE getdat_mod
  INTERFACE
SUBROUTINE GETDAT(REQ,IPOS,ICENT,ITIME,IFORM,TRANGE,IFAIL, &  !2.0
                  CERR)                                       !2.0

IMPLICIT NONE

! Subroutine arguments:

CHARACTER(*), INTENT(INOUT)     :: REQ
INTEGER, INTENT(INOUT)          :: IPOS
INTEGER, INTENT(INOUT)          :: ICENT
INTEGER, INTENT(INOUT)          :: ITIME(4)
INTEGER, INTENT(INOUT)          :: IFORM
INTEGER, INTENT(INOUT)          :: TRANGE
INTEGER, INTENT(INOUT)          :: IFAIL
CHARACTER(*), INTENT(INOUT)     :: CERR

END SUBROUTINE GETDAT
END INTERFACE
END MODULE getdat_mod
