MODULE gethdr_mod
  INTERFACE
    SUBROUTINE GETHDR (TYPES, NTYPES)
      IMPLICIT NONE
      INTEGER,         INTENT(INOUT) :: NTYPES   ! (2) NUMBER OF DATA TYPES
      CHARACTER(LEN=8),INTENT(IN)    :: TYPES(NTYPES) ! (1) LIST OF WANTED DATA TYPES
    END SUBROUTINE GETHDR
  END INTERFACE
END MODULE gethdr_mod
