MODULE getstr_mod
  INTERFACE
SUBROUTINE GETSTR(REQ,IPOS,ILEN,CIDENT,INUM,IDLEN,ISTYP, &
                  IFAIL,CERR)

IMPLICIT NONE

! Subroutine arguments:

CHARACTER(*), INTENT(INOUT)     ::  REQ
INTEGER, INTENT(INOUT)          ::  IPOS
INTEGER, INTENT(INOUT)          ::  ILEN
CHARACTER(*), INTENT(INOUT)     ::  CIDENT(:)
INTEGER, INTENT(INOUT)          ::  INUM
INTEGER, INTENT(INOUT)          ::  IDLEN
INTEGER, INTENT(INOUT)          ::  ISTYP
INTEGER, INTENT(INOUT)          ::  IFAIL
CHARACTER(*), INTENT(INOUT)     ::  CERR

END SUBROUTINE GETSTR
END INTERFACE
END MODULE getstr_mod
