MODULE getstn_mod
  INTERFACE
SUBROUTINE GETSTN(REQ,IPOS,ILEN,ISTN,INUM,IDLEN,ISTYP, &
                     IFAIL,CERR)
IMPLICIT NONE

! Subroutine arguments:

CHARACTER(*), INTENT(INOUT)     ::  REQ
INTEGER, INTENT(INOUT)          ::  IPOS
INTEGER, INTENT(INOUT)          ::  ILEN
INTEGER, INTENT(INOUT)          ::  ISTN(:)
INTEGER, INTENT(INOUT)          ::  INUM
INTEGER, INTENT(INOUT)          ::  IDLEN
INTEGER, INTENT(INOUT)          ::  ISTYP
INTEGER, INTENT(INOUT)          ::  IFAIL
CHARACTER(*), INTENT(INOUT)     ::  CERR

END SUBROUTINE GETSTN
END INTERFACE
END MODULE getstn_mod
