MODULE gribread_mod
  INTERFACE
SUBROUTINE GRIBREAD (IUNIT, LENREC, LEFT, NCOPIED, RECORD, KODE)

IMPLICIT NONE

! Subroutine arguments:

INTEGER, INTENT(IN)             ::  IUNIT ! UNIT NUMBER FOR GRIB DATA SET
INTEGER, INTENT(IN)             ::  LENREC ! RECORD LENGTH OF GRIB DATA SET
INTEGER, INTENT(INOUT)          ::  LEFT ! SET TO NUMBER OF BYTES IN MESSAGE IF NEW D/S
INTEGER, INTENT(OUT)            ::  NCOPIED ! BYTES IN RECORD BEFORE NEXT TO COPY
CHARACTER(*), INTENT(OUT)       ::  RECORD ! TO HOLD ONE RECORD OF GR   IB DATA
INTEGER, INTENT(OUT)            ::  KODE ! OUTPUT STATUS CODE - SEE ABOVE

END SUBROUTINE GRIBREAD
END INTERFACE
END MODULE gribread_mod
