MODULE gribfind_mod
  INTERFACE
SUBROUTINE GRIBFIND (DATYPE, IDATA, ITIME, ISELECT, KEYWRD, & !2.3
                     LTEST, KODE, IUNIT, LENREC)              !2.3

IMPLICIT NONE

! Subroutine arguments:

CHARACTER(*), INTENT(IN)        ::  DATYPE ! MET.D.B. GRIB DATA TYPE
INTEGER, INTENT(IN)             ::  IDATA(5) ! INFORMATION ABOUT INDEX DATA SET (SEE ABOVE)
INTEGER, INTENT(IN)             ::  ITIME(8) ! START AND END TIMES OF REQUEST PERIOD
INTEGER, INTENT(IN)             ::  ISELECT(50) ! ARRAY OF DATA SELECTION PARAMETERS !3
LOGICAL, INTENT(IN)             ::  KEYWRD(:) ! MDB KEYWORDS (= ARRAY 'FOUND' IN 'MDB') !2.3
LOGICAL, INTENT(IN)             ::  LTEST ! .TRUE. FOR EXTRA PRINTOUT (PASSED TO GRIBOPEN)
INTEGER, INTENT(INOUT)          ::  KODE ! STATUS CODE RETURNED BY THIS ROUTINE
INTEGER, INTENT(OUT)            ::  IUNIT ! UNIT NUMBER FOR GRIB DATA SET (FROM GRIBOPEN)
INTEGER, INTENT(OUT)            ::  LENREC ! RECORD LENGTH OF GRIB DATA SET

END SUBROUTINE GRIBFIND
END INTERFACE
END MODULE gribfind_mod
