MODULE gribindx_mod
  INTERFACE
SUBROUTINE GRIBINDX (DSNX, IDATA, ITIME, KODE)

IMPLICIT NONE

! Subroutine arguments:

CHARACTER(*), INTENT(IN)        ::  DSNX ! NAME OF INDEX DATA SET
INTEGER, INTENT(IN)             ::  IDATA(5) ! INFORMATION ABOUT INDEX DATA SET (SEE ABOVE)
INTEGER, INTENT(INOUT)          ::  ITIME(8) ! START AND END TIMES OF REQUEST PERIOD
INTEGER, INTENT(OUT)            ::  KODE ! STATUS CODE RETURNED BY THIS ROUTINE

END SUBROUTINE GRIBINDX
END INTERFACE
END MODULE gribindx_mod
