MODULE gtgrp_mod
  INTERFACE
SUBROUTINE GTGRP(SP,STACK,BASE,TMPELM,IREP,NUMBER,IERR)

IMPLICIT NONE

! Subroutine arguments:

INTEGER, INTENT(INOUT)          ::  SP
CHARACTER(1), INTENT(INOUT)     ::  STACK(:)
INTEGER, INTENT(IN)             ::  BASE
CHARACTER(36), INTENT(OUT)      ::  TMPELM(:)
INTEGER, INTENT(IN)             ::  IREP
INTEGER, INTENT(INOUT)          ::  NUMBER
INTEGER, INTENT(OUT)            ::  IERR

END SUBROUTINE GTGRP
END INTERFACE
END MODULE gtgrp_mod
