MODULE hkstop_mod
  INTERFACE
    SUBROUTINE HKSTOP (RECORD, KODE)

    IMPLICIT NONE

! Subroutine arguments:

    CHARACTER(LEN=*), INTENT(INOUT) :: RECORD(*) !a01 HOUSEKEEPING RECORDS
    INTEGER,          INTENT(INOUT) :: KODE      !a02 RETURN CODE

    END SUBROUTINE HKSTOP
  END INTERFACE
END MODULE hkstop_mod
