MODULE hkstart_mod
  INTERFACE
    SUBROUTINE HKSTART (CLEAR, STORTYPE, NSTORE, RECORD, NDAY0, NSEC0)

    IMPLICIT NONE

! Subroutine arguments:

    LOGICAL,          INTENT(IN)    :: CLEAR            !a01 FLAG FOR TOTAL CLEAROUT OF H.K.
    INTEGER,          INTENT(IN)    :: NSTORE           !a03 NUMBER OF STORAGE TYPES REQUIRED
    CHARACTER(LEN=8), INTENT(IN)    :: STORTYPE(NSTORE) !a02 ARRAY OF STORAGE TYPES REQUIRED
    CHARACTER(LEN=*), INTENT(OUT)   :: RECORD(:)        !a04 STARTING INFORMATION ON DATA SETS
    INTEGER,          INTENT(OUT)   :: NDAY0            !a05 START CENTURY DAY
    INTEGER,          INTENT(OUT)   :: NSEC0            !a06 START SECONDS FROM 00Z

    END SUBROUTINE HKSTART
  END INTERFACE
END MODULE hkstart_mod
