MODULE hkupdate_mod
  INTERFACE
    SUBROUTINE HKUPDATE (RECORD)

    IMPLICIT NONE

! Subroutine arguments:

    CHARACTER(LEN=*), INTENT(INOUT) :: RECORD(*) !a01 HOUSEKEEPING RECORDS

    END SUBROUTINE HKUPDATE
  END INTERFACE
END MODULE hkupdate_mod
