MODULE IDES_mod
  INTERFACE
    FUNCTION IDES(FXXYYY) RESULT(IDES_0)
      IMPLICIT NONE
      INTEGER :: FXXYYY
      INTEGER :: IDES_0
    END FUNCTION IDES
  END INTERFACE
END MODULE IDES_mod
