MODULE index1_mod
 INTERFACE
  SUBROUTINE INDEX1 (MESSAGE, FLAGS, ITEMS, NTIME, ENTRY, KODE)
   CHARACTER(LEN=*),INTENT(IN)   :: MESSAGE
   LOGICAL,INTENT(IN)            :: FLAGS(9)
   INTEGER,INTENT(IN)            :: ITEMS(12)
   INTEGER,INTENT(OUT)           :: NTIME(6,2)
   CHARACTER(LEN=26),INTENT(OUT) :: ENTRY
   INTEGER,INTENT(OUT)           :: KODE
  END SUBROUTINE INDEX1
 END INTERFACE
END MODULE index1_mod
