MODULE initstor_mod
  INTERFACE
    SUBROUTINE INITSTOR (HEAD1, HEAD2, BULTYP, FLAGS, ITEMS, &
     NBULLS, LENIDX, LSEQ, BUFFER)

    IMPLICIT NONE

    CHARACTER(LEN=6),INTENT(OUT)  :: HEAD1(:)   ! (1) START OF EACH BULL RANGE
    CHARACTER(LEN=6),INTENT(OUT)  :: HEAD2(:)   ! (2) END OF EACH BULL RANGE
    CHARACTER(LEN=8),INTENT(OUT)  :: BULTYP(:)  ! (3) DATA TYPE ARRAY
                                             !(NAMES UP TO 8 CHARS)
    LOGICAL,         INTENT(OUT)   :: FLAGS(:,:)   ! (4) PROCESSING FLAGS
    INTEGER,         INTENT(INOUT) :: ITEMS(0:,:) ! (5) PROC CONTROL DATA
    INTEGER,         INTENT(INOUT) :: NBULLS    ! (6) NUMBER OF BULLETIN RANGES FOUND
    INTEGER,         INTENT(OUT)   :: LENIDX(:) ! (7) LEN OF IDX ENT FOR OPEN FILES
    INTEGER,         INTENT(OUT)   :: LSEQ(:)   ! (8) LOCAL DESCRIPTORS FOR OPEN FILES
    CHARACTER(LEN=*),INTENT(INOUT) :: BUFFER    ! (9) CHAR BUFFER (FOR INTERNAL USE)

    END SUBROUTINE INITSTOR
  END INTERFACE
END MODULE initstor_mod  
