MODULE initbull_mod
  INTERFACE
    SUBROUTINE INITBULL (HEAD1, HEAD2, BULTYP, FLAGS, ITEMS, NBULLS, &
                         STORTYPE, NSTORE)
    IMPLICIT NONE

! Subroutine arguments:

    CHARACTER(LEN=6), INTENT(OUT)   :: HEAD1(*)          !a01 START OF EACH BULLETIN RANGE
    CHARACTER(LEN=6), INTENT(OUT)   :: HEAD2(*)          !a02 END OF EACH BULLETIN RANGE
    CHARACTER(LEN=8), INTENT(OUT)   :: BULTYP(*)         !a03 DATA TYPE ARRAY (NAMES UP TO 8 CHARS)
    LOGICAL,          INTENT(OUT)   :: FLAGS(:,:)        !a04 PROCESSING FLAGS
    INTEGER,          INTENT(OUT)   :: ITEMS(0:,:)       !a05 PROCESSING CONTROL DATA
    INTEGER,          INTENT(INOUT) :: NBULLS            !a06 NUMBER OF BULLETIN RANGES FOUND
    CHARACTER(LEN=8), INTENT(OUT)   :: STORTYPE(*)       !a07 LIST OF STORAGE DATA TYPES NEEDED
    INTEGER,          INTENT(INOUT) :: NSTORE            !a08 NUMBER OF STORAGE DATA SETS REQUIRED

    END SUBROUTINE INITBULL
  END INTERFACE
END MODULE initbull_mod
