MODULE ioblks_mod
 INTERFACE
  SUBROUTINE IOBLKS (MODE, IUNIT, LENREC, NRECS, NREC1,&
                          NUNIT, NREC, BUFFER)
   INTEGER,INTENT(IN)            :: MODE
   INTEGER,INTENT(IN)            :: IUNIT
   INTEGER,INTENT(IN)            :: LENREC
   INTEGER,INTENT(IN)            :: NRECS
   INTEGER,INTENT(IN)            :: NREC1
   INTEGER,INTENT(INOUT)         :: NUNIT(NRECS)
   INTEGER,INTENT(INOUT)         :: NREC(NRECS)
   CHARACTER(LEN=*),INTENT(OUT)  :: BUFFER(:)
  END SUBROUTINE IOBLKS
 END INTERFACE
END MODULE ioblks_mod
