MODULE LOCALD_mod
  INTERFACE
    SUBROUTINE LOCALD(X,Y,SEQ,NSEQ,TEXT,MODE)
      IMPLICIT NONE
      INTEGER,INTENT(IN)          ::  X
      INTEGER,INTENT(IN)          ::  Y
      INTEGER,INTENT(OUT)         ::  NSEQ
      INTEGER,INTENT(OUT)         ::  SEQ(*)
      CHARACTER(LEN=*),INTENT(IN) ::  TEXT
      CHARACTER(LEN=*),INTENT(IN) ::  MODE
    END SUBROUTINE LOCALD
  END INTERFACE
END MODULE LOCALD_mod
