MODULE mdb_mod
  INTERFACE
SUBROUTINE MDB(CTYPE,REQUEST,RVALS,NOBS,NELEM,STATUS,CSTR,CREPT)

IMPLICIT NONE

! Subroutine arguments:

CHARACTER(*), INTENT(IN)        ::  CTYPE
CHARACTER(*), INTENT(IN)        ::  REQUEST
INTEGER, INTENT(INOUT)          ::  NOBS
INTEGER, INTENT(IN)             ::  NELEM
REAL, INTENT(OUT)               ::  RVALS(NOBS,NELEM)
INTEGER, INTENT(INOUT)          ::  STATUS
CHARACTER(*), INTENT(OUT)       ::  CSTR(NOBS)
CHARACTER(*), INTENT(OUT)       ::  CREPT(NOBS)

END SUBROUTINE MDB
END INTERFACE
END MODULE mdb_mod
