MODULE mdbbd_mod
  INTERFACE
    SUBROUTINE MDBBD(CSUBT, MDBBD_CREQ, MDBBD_ARRAY, MDBBD_NOBS,  &
                 MDBBD_NELEM, MDBBD_ISTAT, MDBBD_CSTR, MBUFR, &
                 LMBUFR, NMBUFR)
    IMPLICIT NONE
    CHARACTER(*),INTENT(INOUT) ::  CSUBT
    CHARACTER(*),INTENT(IN)    ::  MDBBD_CREQ
    INTEGER,INTENT(INOUT)      ::  MDBBD_NOBS
    INTEGER,INTENT(IN)         ::  MDBBD_NELEM
    REAL,INTENT(OUT)           ::  MDBBD_ARRAY(MDBBD_NOBS,MDBBD_NELEM)
    INTEGER,INTENT(INOUT)      ::  MDBBD_ISTAT
    CHARACTER(*),INTENT(OUT)   ::  MDBBD_CSTR(MDBBD_NOBS)
    CHARACTER(*),INTENT(IN)    ::  MBUFR
    INTEGER,INTENT(IN)         ::  LMBUFR(*)
    INTEGER,INTENT(IN)         ::  NMBUFR
    END SUBROUTINE MDBBD
  END INTERFACE
END MODULE mdbbd_mod
