MODULE mdblseq_mod
  INTERFACE
    SUBROUTINE MDBLSEQ(CSUBT,MATCH)

    IMPLICIT NONE
    CHARACTER(*),INTENT(IN) ::  CSUBT
    LOGICAL,INTENT(OUT)     ::  MATCH
    END SUBROUTINE MDBLSEQ
  END INTERFACE
END MODULE mdblseq_mod
