MODULE mdbrsn_mod
  INTERFACE
    SUBROUTINE MDBRSN(RQSTDSN,RESTDSN,MSTREAM,RC)
      IMPLICIT NONE
      CHARACTER(LEN=44),INTENT(IN)  :: RQSTDSN
      CHARACTER(LEN=44),INTENT(IN)  :: RESTDSN
      CHARACTER(LEN=3) ,INTENT(IN)  :: MSTREAM
      INTEGER          ,INTENT(OUT) :: RC
    END SUBROUTINE MDBRSN
  END INTERFACE
END MODULE mdbrsn_mod

