MODULE mermdb_mod
  INTERFACE
SUBROUTINE MERMDB(DATA,MODE,REQUESTS,LMLIST,NMDB,MAXNOBS,&
                  NOBSMDB,DBDATA,DIM,CSTR,CSTRDIM,REPTXT,IVERT,MDBRC)
IMPLICIT  NONE

CHARACTER(*) :: DATA
CHARACTER(*) :: MODE
CHARACTER(*) :: REQUESTS
CHARACTER(*) :: LMLIST
INTEGER   :: NMDB
INTEGER   :: MAXNOBS
INTEGER   :: NOBSMDB
INTEGER   :: DIM
REAL      :: DBDATA(DIM)
INTEGER   :: CSTRDIM
CHARACTER(*)  :: CSTR(CSTRDIM)
CHARACTER*(*) :: REPTXT
INTEGER   :: IVERT
INTEGER   :: MDBRC
      END SUBROUTINE MERMDB
    END INTERFACE
END MODULE mermdb_mod
