MODULE mersy9_mod
  INTERFACE
      SUBROUTINE MERSY9(REPTXT,OUTMESS,REPLEN,REPLEN9)
      IMPLICIT NONE
      CHARACTER REPTXT*(*)
      CHARACTER OUTMESS*(*)
      INTEGER REPLEN
      INTEGER REPLEN9
      END SUBROUTINE MERSY9
  END INTERFACE
END MODULE mersy9_mod
