MODULE merval_mod
  INTERFACE
      SUBROUTINE MERVAL(STRING,IBEFOR,WIDTH,VALUE)
      CHARACTER STRING*(*)
      INTEGER IBEFOR
      INTEGER WIDTH
      INTEGER VALUE
      END SUBROUTINE MERVAL
  END INTERFACE
END MODULE merval_mod
