MODULE mnthds_mod
 INTERFACE
  INTEGER FUNCTION MNTHDS(MONTH,YEAR)
   IMPLICIT NONE
   INTEGER, INTENT(IN)  :: MONTH
   INTEGER, INTENT(IN)  :: YEAR
  END INTEGER FUNCTION MNTHDS
 END INTERFACE 
END FUNCTION MNTHDS
