MODULE mobsto_mod
  INTERFACE
    SUBROUTINE MOBSTO (DATIME, ENTRY, BULL, IFT, BLKSIZ, IDENT)
    IMPLICIT NONE

! Arguments

    INTEGER,         INTENT(INOUT) :: DATIME(5)
    CHARACTER(LEN=*),INTENT(INOUT) :: ENTRY
    CHARACTER(LEN=*),INTENT(IN)    :: BULL
    INTEGER,         INTENT(IN)    :: IFT
    INTEGER,         INTENT(IN)    :: BLKSIZ
    CHARACTER(LEN=*),INTENT(IN)    :: IDENT
    END SUBROUTINE MOBSTO
  END INTERFACE
END MODULE mobsto_mod
