MODULE modlva_mod
  INTERFACE
      SUBROUTINE MODLVA(IFT,BUFMES,L,IRC)
      IMPLICIT NONE
      INTEGER IFT
      INTEGER IRC
      INTEGER L
      CHARACTER           BUFMES*(*)
      END SUBROUTINE MODLVA
  END INTERFACE
END MODULE modlva_mod
