MODULE MTRGRP_MOD
INTERFACE
SUBROUTINE MTRGRP(GROUP,LENGTH,NCHAR,CHARR)

IMPLICIT NONE

CHARACTER (LEN=*),  INTENT(IN)    ::  GROUP
INTEGER,            INTENT(IN)    ::  LENGTH
INTEGER,            INTENT(OUT)   ::  NCHAR
CHARACTER (LEN=*),  INTENT(OUT)   ::  CHARR

END SUBROUTINE MTRGRP
END INTERFACE
END MODULE MTRGRP_MOD
