MODULE MTRLOC_MOD
INTERFACE
SUBROUTINE MTRLOC(REPLEN,REPORT,POINT,GRPLEN,LREPFL)

INTEGER,           INTENT(IN)    ::  REPLEN
CHARACTER (LEN=*), INTENT(IN)    ::  REPORT
INTEGER,           INTENT(INOUT) ::  POINT
INTEGER,           INTENT(OUT)   ::  GRPLEN
LOGICAL,           INTENT(OUT)   ::  LREPFL

END SUBROUTINE MTRLOC
END INTERFACE
END MODULE MTRLOC_MOD
