MODULE nchtst_mod
  INTERFACE
    SUBROUTINE NCHTST(POINT,LENGTH,ALLFIG,INUMB,OSPACE,OLFCR,BULL)

    IMPLICIT NONE

! Subroutine arguments:

    INTEGER,          INTENT(IN)    :: POINT !A1
    INTEGER,          INTENT(IN)    :: LENGTH !A2
    LOGICAL,          INTENT(OUT)   :: ALLFIG !A3
    INTEGER,          INTENT(OUT)   :: INUMB !A4
    LOGICAL,          INTENT(OUT)   :: OSPACE !A5
    LOGICAL,          INTENT(OUT)   :: OLFCR !A6
    CHARACTER(LEN=*), INTENT(IN)    :: BULL !A7

    END SUBROUTINE NCHTST
  END INTERFACE
END MODULE nchtst_mod
