MODULE nextmsg_mod
  INTERFACE
    SUBROUTINE NEXTMSG (NFT, MESAGE, MSTART, MLNGTH, MSGCODE)
    IMPLICIT NONE
    INTEGER,         INTENT(IN)    :: NFT      ! UNIT NUMBER OF MESSAGE FILE
    CHARACTER(LEN=*),INTENT(INOUT) :: MESAGE
    INTEGER,         INTENT(OUT)   :: MSTART   ! POINTER TO START OF MESS
    INTEGER,         INTENT(OUT)   :: MLNGTH   ! LEN OF MESSAGE 
    INTEGER,         INTENT(OUT)   :: MSGCODE  ! RETURN CODE FROM "NEXTMSG"
    END SUBROUTINE NEXTMSG
  END INTERFACE
END MODULE nextmsg_mod
