MODULE nextfile_mod
  INTERFACE
    SUBROUTINE NEXTFILE (DSN, NBULLS, STOPFLAG)

    IMPLICIT NONE

    CHARACTER (LEN=*), INTENT(INOUT)  :: DSN       ! NAME OF NEXT DATA SET TO PROCESS
    INTEGER, INTENT(INOUT)            :: NBULLS    ! WANTED BULLETINS IN NEXT DATA SET
    LOGICAL, INTENT(INOUT)            :: STOPFLAG  ! .TRUE. IF JOB TERMINATION IS REQUIRED

    END SUBROUTINE NEXTFILE
  END INTERFACE
END MODULE nextfile_mod
