MODULE NMSTEM_MOD
INTERFACE
SUBROUTINE NMSTEM(CNAME,CSTEM,CINST)


IMPLICIT NONE

CHARACTER (LEN=*), INTENT(IN)  ::  CNAME
CHARACTER (LEN=*), INTENT(OUT) ::  CSTEM
CHARACTER (LEN=*), INTENT(OUT) ::  CINST

END SUBROUTINE NMSTEM
END INTERFACE
END MODULE NMSTEM_MOD
