MODULE ofigts_mod
  INTERFACE
    LOGICAL FUNCTION OFIGTS(CSTR,ISTART,IEND)

IMPLICIT NONE

CHARACTER(*), INTENT(IN) ::  CSTR
INTEGER,      INTENT(IN) ::  ISTART
INTEGER,      INTENT(IN) ::  IEND

    END FUNCTION OFIGTS
  END INTERFACE
END MODULE ofigts_mod
