MODULE ONLAND_mod
  INTERFACE
    LOGICAL FUNCTION ONLAND(RLAT,RLONG)

    IMPLICIT NONE

    REAL, INTENT(IN)  :: RLAT
    REAL, INTENT(IN)  :: RLONG

    END FUNCTION ONLAND
  END INTERFACE
END MODULE ONLAND_mod
