MODULE parse_mod
  INTERFACE
    SUBROUTINE PARSE(CHAR,SP,STACK,IREP,OBRKT,CBRKT,LEVEL,NEST,IERR, &
                     EXPECT,NEXT)

    IMPLICIT NONE

! Subroutine arguments:

    CHARACTER(1), INTENT(IN)    ::  CHAR
    INTEGER,      INTENT(INOUT) ::  SP
    CHARACTER(1), INTENT(INOUT) ::  STACK(:)
    INTEGER,      INTENT(INOUT) ::  IREP
    INTEGER,      INTENT(INOUT) ::  OBRKT
    INTEGER,      INTENT(INOUT) ::  CBRKT
    INTEGER,      INTENT(INOUT) ::  LEVEL(:)
    INTEGER,      INTENT(INOUT) ::  NEST
    INTEGER,      INTENT(OUT)   ::  IERR
    LOGICAL,      INTENT(INOUT) ::  EXPECT
    CHARACTER(1), INTENT(INOUT) ::  NEXT

    END SUBROUTINE PARSE
  END INTERFACE
END MODULE parse_mod
