MODULE push_mod
  INTERFACE
    SUBROUTINE PUSH(SP, ELEM, STACK, IERR)

    IMPLICIT NONE

! Subroutine arguments:

    INTEGER,      INTENT(INOUT) ::  SP
    CHARACTER(1), INTENT(IN)    ::  ELEM
    CHARACTER(1), INTENT(INOUT) ::  STACK(:)
    INTEGER,      INTENT(OUT)   ::  IERR

    END SUBROUTINE PUSH
  END INTERFACE
END MODULE push_mod
