MODULE RDBITAB_mod
 INTERFACE
  SUBROUTINE RDBITAB(CINDEX,LOCALD,BINDEX,NDEX,MESTRUCT,BINMAX,&
   &LFLAG,IFAIL)
    CHARACTER(LEN=*) ::  CINDEX(*)
    INTEGER          ::  BINMAX
    INTEGER          ::  IFAIL
    INTEGER          ::  NDEX
    CHARACTER(LEN=6) ::  LOCALD
    CHARACTER(LEN=*) ::  BINDEX(BINMAX)
    CHARACTER(LEN=*) ::  MESTRUCT
    LOGICAL          ::  LFLAG
   END SUBROUTINE RDBITAB
 END INTERFACE
END MODULE RDBITAB_mod
