MODULE readidx_mod
 INTERFACE
  SUBROUTINE READIDX(SubType,CINDX,Xtype,Match)
   LOGICAL          ::  MATCH
   CHARACTER(LEN=*) ::  CINDX(:)
   CHARACTER(LEN=8) ::  SubType
   CHARACTER(LEN=1) ::  XTYPE
  END SUBROUTINE READIDX
 END INTERFACE
END MODULE readidx_mod
