MODULE repedt_mod
  INTERFACE
    SUBROUTINE REPEDT(BULL,REPORT,REPLEN)

    IMPLICIT NONE

! Subroutine arguments:

    CHARACTER(LEN=*), INTENT(INOUT) :: BULL   !A01
    CHARACTER(LEN=*), INTENT(OUT)   :: REPORT !A02
    INTEGER,          INTENT(INOUT) :: REPLEN !A03

    END SUBROUTINE REPEDT
  END INTERFACE
END MODULE repedt_mod
