MODULE sambul_mod
  INTERFACE
    SUBROUTINE SAMBUL(POINT,BEND,TTAAII,CCCC,YYGGGG, &
                      AMD,AMDNUB,COR,CORNUB,NFT,OERR,BULL)

    IMPLICIT NONE

! Subroutine arguments:

    INTEGER,          INTENT(INOUT) :: POINT !A1
    INTEGER,          INTENT(IN)    :: BEND !A2
    CHARACTER(LEN=6), INTENT(IN)    :: TTAAII !A3
    CHARACTER(LEN=4), INTENT(IN)    :: CCCC !A4
    CHARACTER(LEN=6), INTENT(IN)    :: YYGGGG !A5
    LOGICAL,          INTENT(IN)    :: AMD !A6
    CHARACTER(LEN=2), INTENT(IN)    :: AMDNUB !A7 FOR WHOLE BULLETIN
    LOGICAL,          INTENT(IN)    :: COR !A8
    CHARACTER(LEN=2), INTENT(IN)    :: CORNUB !A9 FOR WHOLE BULLETIN
    INTEGER,          INTENT(IN)    :: NFT !A10
    LOGICAL,          INTENT(OUT)   :: OERR !A11
    CHARACTER(LEN=*), INTENT(INOUT) :: BULL !A12

    END SUBROUTINE SAMBUL
  END INTERFACE
END MODULE sambul_mod
