MODULE SATBBN_mod
  INTERFACE
    SUBROUTINE SATBBN(POINT,CRUDELAT,CRUDELON,NORTH,EAST,NN,BULL)

    IMPLICIT NONE

    INTEGER, INTENT(IN)               :: POINT
    INTEGER, INTENT(OUT)              :: CRUDELAT
    INTEGER, INTENT(OUT)              :: CRUDELON
    LOGICAL, INTENT(OUT)              :: NORTH
    LOGICAL, INTENT(OUT)              :: EAST
    INTEGER, INTENT(OUT)              :: NN
    CHARACTER (LEN=*), INTENT(INOUT)  :: BULL

    END SUBROUTINE SATBBN
  END INTERFACE
END MODULE SATBBN_mod
