MODULE SATOB4_mod
  INTERFACE
    SUBROUTINE SATOB4(POINT,DCVALS,NOBS,BULL)

    IMPLICIT NONE

    INTEGER, INTENT(INOUT)            :: POINT
    REAL, INTENT(OUT)                 :: DCVALS(:)
    INTEGER, INTENT(IN)               :: NOBS
    CHARACTER (LEN=*), INTENT(INOUT)  :: BULL

    END SUBROUTINE SATOB4
  END INTERFACE
END MODULE SATOB4_mod
