MODULE SATOB2_mod
  INTERFACE
    SUBROUTINE SATOB2(POINT,KNOTS,DCVALS,NOBS,BULL,SLASHES)

    IMPLICIT NONE

    INTEGER, INTENT(INOUT)            :: POINT
    LOGICAL, INTENT(IN)               :: KNOTS
    REAL, INTENT(OUT)                 :: DCVALS(:)
    INTEGER, INTENT(IN)               :: NOBS
    CHARACTER (LEN=*), INTENT(INOUT)  :: BULL
    LOGICAL, INTENT(IN)               :: SLASHES

    END SUBROUTINE SATOB2
  END INTERFACE
END MODULE SATOB2_mod
