MODULE SATOB1_mod
  INTERFACE
    SUBROUTINE SATOB1(NFT,POINT,BULLEND,BULL,TTAAII,CCCC,OCOR)

    IMPLICIT NONE

    INTEGER, INTENT(IN)               :: NFT
    INTEGER, INTENT(INOUT)            :: POINT
    INTEGER, INTENT(IN)               :: BULLEND
    CHARACTER (LEN=*), INTENT(INOUT)  :: BULL
    CHARACTER (LEN=*), INTENT(IN)     :: TTAAII
    CHARACTER (LEN=*), INTENT(IN)     :: CCCC
    LOGICAL, INTENT(IN)               :: OCOR

    END SUBROUTINE SATOB1
  END INTERFACE
END MODULE SATOB1_mod
