MODULE SATOB7_mod
  INTERFACE
    SUBROUTINE SATOB7(POINT,DCVALS,NOBS,BULL)

    IMPLICIT NONE

    INTEGER, INTENT(INOUT)            :: POINT
    REAL, INTENT(OUT)                 :: DCVALS(:)
    INTEGER, INTENT(IN)               :: NOBS
    CHARACTER (LEN=*), INTENT(INOUT)  :: BULL

    END SUBROUTINE SATOB7
  END INTERFACE
END MODULE SATOB7_mod
