MODULE SATOB5_mod
  INTERFACE
    SUBROUTINE SATOB5(POINT,DCVALS,NOBS,BULL)

    IMPLICIT NONE

    INTEGER, INTENT(INOUT)            :: POINT
    REAL, INTENT(OUT)                 :: DCVALS(:)
    INTEGER, INTENT(IN)               :: NOBS
    CHARACTER (LEN=*), INTENT(INOUT)  :: BULL

    END SUBROUTINE SATOB5
  END INTERFACE
END MODULE SATOB5_mod
