MODULE sfdate_mod
  INTERFACE
    SUBROUTINE SFDATE(HOUR,YYGGGG,DATIME)

    IMPLICIT NONE

! Arguments

    INTEGER,          INTENT(IN) :: HOUR     !(1)
    CHARACTER(LEN=6), INTENT(IN) :: YYGGGG   !(2)
    INTEGER,          INTENT(OUT):: DATIME(5)!(3)

    END SUBROUTINE SFDATE
  END INTERFACE
END MODULE sfdate_mod
