MODULE SKLARR_MOD
  INTERFACE
    SUBROUTINE SKLARR (IDESC,NELEM,IREPL,QCREQ,ELMNUM,SEGNUM,SUBNUM, &
                       NROWS,SEGMENT,IVAL,NELREQ,QCINC,NSEGS,SEGLEN, &
                       NVALEN,LFLAG)
    IMPLICIT NONE
!                              Subroutine arguments

    INTEGER,  INTENT(IN)    :: NELEM
    INTEGER,  INTENT(IN)    :: IDESC(NELEM)
    INTEGER,  INTENT(IN)    :: IREPL(NELEM)
    LOGICAL,  INTENT(IN)    :: QCREQ
    INTEGER,  INTENT(IN)    :: NROWS
    INTEGER,  INTENT(IN)    :: ELMNUM(NROWS)
    INTEGER,  INTENT(IN)    :: SEGNUM(NROWS)
    INTEGER,  INTENT(IN)    :: SUBNUM(NROWS)
    INTEGER,  INTENT(INOUT) :: SEGMENT(:)
    INTEGER,  INTENT(INOUT) :: IVAL(:)
    INTEGER,  INTENT(OUT)   :: NELREQ
    INTEGER,  INTENT(IN)    :: QCINC
    INTEGER,  INTENT(IN)    :: NSEGS
    INTEGER,  INTENT(IN)    :: SEGLEN(NSEGS)
    INTEGER,  INTENT(OUT)   :: NVALEN(NSEGS)
    LOGICAL,  INTENT(IN)    :: LFLAG

    END SUBROUTINE SKLARR
  END INTERFACE
END MODULE SKLARR_MOD
