MODULE SKLDSP_MOD
  INTERFACE
    SUBROUTINE SKLDSP (IDESC,NELEM,IREPL,LMINDEX,NINDEX,MESTRUCT,    &
                       QCREQ,SEGMENT,IBEFOR,WIDTH,SCALE,REFVAL,      &
                       NELREQ,NSEG,NWID,NREPLEN,MAXELM,MAXSEG,LFLAG, &
                       BINMAX)
    IMPLICIT NONE
!                                  Subroutine arguments

    INTEGER,       INTENT(IN)  ::  NELEM
    INTEGER,       INTENT(IN)  ::  IDESC(NELEM)
    INTEGER,       INTENT(IN)  ::  IREPL(NELEM)
    INTEGER,       INTENT(IN)  ::  BINMAX
    CHARACTER(*),  INTENT(IN)  ::  LMINDEX(BINMAX)
    INTEGER,       INTENT(IN)  ::  NINDEX
    CHARACTER(*),  INTENT(IN)  ::  MESTRUCT
    LOGICAL,       INTENT(IN)  ::  QCREQ
    INTEGER,       INTENT(IN)  ::  MAXELM
    INTEGER,       INTENT(OUT) ::  SEGMENT(MAXELM)
    INTEGER,       INTENT(OUT) ::  IBEFOR(MAXELM)
    INTEGER,       INTENT(OUT) ::  WIDTH(MAXELM)
    INTEGER,       INTENT(OUT) ::  SCALE(MAXELM)
    INTEGER,       INTENT(OUT) ::  REFVAL(MAXELM)
    INTEGER,       INTENT(OUT) ::  NELREQ
    INTEGER,       INTENT(OUT) ::  NSEG
    INTEGER,       INTENT(IN)  ::  MAXSEG
    INTEGER,       INTENT(OUT) ::  NWID(MAXSEG)
    INTEGER,       INTENT(OUT) ::  NREPLEN(MAXSEG)
    LOGICAL,       INTENT(IN)  ::  LFLAG

    END SUBROUTINE SKLDSP
  END INTERFACE
END MODULE SKLDSP_MOD
