MODULE SORTCH_MOD
INTERFACE
SUBROUTINE SORTCH(C,L,N,MASK)

IMPLICIT NONE

INTEGER,           INTENT(IN)      ::  L,N
CHARACTER (LEN=*), INTENT(INOUT)   ::  C(N)
CHARACTER (LEN=*), INTENT(IN)      ::  MASK

END SUBROUTINE SORTCH
END INTERFACE
END MODULE SORTCH_MOD
