MODULE SORTN_MOD
INTERFACE
SUBROUTINE SORTN(A,L,N,MASK)

IMPLICIT NONE

INTEGER, INTENT(IN)     :: L,N        ! Dimensions for array
INTEGER, INTENT(INOUT)  :: A(L,N)
INTEGER, INTENT(IN)     :: MASK(L)

END SUBROUTINE SORTN
END INTERFACE
END MODULE SORTN_MOD
