MODULE SORTCHR_MOD
INTERFACE
SUBROUTINE SORTCHR(C,L,N,MASK)

IMPLICIT NONE

INTEGER,           INTENT(IN)      ::  L,N
CHARACTER (LEN=*), INTENT(INOUT)   ::  C(N)
CHARACTER (LEN=*), INTENT(IN)      ::  MASK

END SUBROUTINE SORTCHR
END INTERFACE
END MODULE SORTCHR_MOD
