MODULE stapos_mod
  INTERFACE
    SUBROUTINE STAPOS (REQ_WMONO, TYPE, LAT, LONG, HGPT, HGT, ISTAT)

    IMPLICIT NONE

! Subroutine arguments:

    INTEGER,          INTENT(IN)  :: REQ_WMONO ! TARGET WMO STATION NUMBER
    CHARACTER(LEN=*), INTENT(IN)  :: TYPE      ! TARGET STATION TYPE
    REAL,             INTENT(OUT) :: LAT       ! LAT OF TARGET STATION
    REAL,             INTENT(OUT) :: LONG      ! LONG OF TARGET STATION
    REAL,             INTENT(OUT) :: HGPT      ! SENSOR HEIGHT
    REAL,             INTENT(OUT) :: HGT       ! STATION HEIGHT
    INTEGER,          INTENT(OUT) :: ISTAT     ! ERROR CODE RETURNED TO USER

    END SUBROUTINE STAPOS
  END INTERFACE
END MODULE stapos_mod
