MODULE STBBUL_MOD
  INTERFACE
    SUBROUTINE STBBUL(POINT,BEND,TTAAII,CCCC,OCOR,NFT,BULL)
      INTEGER, INTENT(INOUT)          :: POINT  ! POINTER TO WHERE TO START IN BULLETIN
      INTEGER, INTENT(INOUT)          :: BEND   ! NUMBER OF LAST CHARACTER IN BULLETIN
      CHARACTER(LEN=*), INTENT(IN)    :: TTAAII ! TT TYPE OF BULLETIN
      CHARACTER(LEN=*), INTENT(IN)    :: CCCC   ! ORIGINATING CENTRE FOR BULLETIN
      LOGICAL, INTENT(IN)             :: OCOR   ! CORRCETION FLAG
      INTEGER, INTENT(IN)             :: NFT    ! FT NUMBER FOR SATOB STORAGE
      CHARACTER(LEN=*), INTENT(INOUT) :: BULL   ! REPORT DATA
    END SUBROUTINE STBBUL
  END INTERFACE
END MODULE STBBUL_MOD
