MODULE STBENC_mod
  INTERFACE
    SUBROUTINE STBENC(DCVALS,NELEM,NOBS,DESCR,MESSAGE,MESSLEN,DATETIME)

    IMPLICIT NONE

    REAL, INTENT(INOUT)               :: DCVALS(:)
    INTEGER, INTENT(INOUT)            :: NELEM
    INTEGER, INTENT(INOUT)            :: NOBS
    INTEGER, INTENT(INOUT)            :: DESCR(:)
    CHARACTER (LEN=*), INTENT(INOUT)  :: MESSAGE
    INTEGER, INTENT(INOUT)            :: MESSLEN
    INTEGER, INTENT(INOUT)            :: DATETIME(:)

    END SUBROUTINE STBENC
  END INTERFACE
END MODULE STBENC_mod
