MODULE STDPRHT_mod
  INTERFACE
    INTEGER FUNCTION STDPRHT(BLOCK,STN,LEVEL)

    IMPLICIT NONE

    INTEGER, INTENT(IN)  :: BLOCK
    INTEGER, INTENT(IN)  :: STN
    INTEGER, INTENT(IN)  :: LEVEL

    END FUNCTION STDPRHT
  END INTERFACE
END MODULE STDPRHT_mod
