MODULE STMRET_MOD
INTERFACE
SUBROUTINE STMRET(WMOLST,ICAOLST,DCNNLST,RAINLST,IDTYPE,USERPOS, &
                  STNTYPE,ISTAT,RARRAY,NOBS,NELEM,ARRAY1,CSTR,   &
                  CERROR)

IMPLICIT NONE

INTEGER,            INTENT(INOUT)  :: WMOLST(50)
CHARACTER (LEN=4),  INTENT(INOUT)  :: ICAOLST(50)
INTEGER,            INTENT(INOUT)  :: DCNNLST(50)
INTEGER,            INTENT(INOUT)  :: RAINLST(50)
INTEGER,            INTENT(INOUT)  :: IDTYPE
CHARACTER (LEN=1),  INTENT(INOUT)  :: USERPOS
INTEGER,            INTENT(INOUT)  :: STNTYPE
INTEGER,            INTENT(INOUT)  :: ISTAT
INTEGER,            INTENT(INOUT)  :: NOBS
INTEGER,            INTENT(INOUT)  :: NELEM
REAL,               INTENT(INOUT)  :: RARRAY(NOBS,NELEM)
INTEGER,            INTENT(INOUT)  :: ARRAY1(:)
CHARACTER (LEN=*),  INTENT(INOUT)  :: CSTR(:)
CHARACTER (LEN=48), INTENT(INOUT)  :: CERROR

END SUBROUTINE STMRET
END INTERFACE
END MODULE STMRET_MOD
