MODULE STNFIN_MOD
INTERFACE
SUBROUTINE STNFIN(INDREC2,DETAILS)

USE STNMAS_MOD
IMPLICIT NONE

INTEGER,           INTENT(INOUT)  :: INDREC2
TYPE(STNMAS_DETAILS), INTENT(INOUT)  :: DETAILS

END SUBROUTINE STNFIN
END INTERFACE
END MODULE STNFIN_MOD
