MODULE STNINDX_MOD
INTERFACE
SUBROUTINE STNINDX(WMOLST,ICAOLST,DCNNLST,RAINLST, &
                   IDTYPE,POS,ISTAT,INDREC,INDWMO,NFOUND)

IMPLICIT NONE

INTEGER,           INTENT(IN)  :: WMOLST(49)
CHARACTER (LEN=4), INTENT(IN)  :: ICAOLST(49)
INTEGER,           INTENT(IN)  :: DCNNLST(49)
INTEGER,           INTENT(IN)  :: RAINLST(49)
INTEGER,           INTENT(IN)  :: IDTYPE
CHARACTER (LEN=1), INTENT(IN)  :: POS
INTEGER,           INTENT(OUT) :: ISTAT
INTEGER,           INTENT(OUT) :: INDREC(1000)
INTEGER,           INTENT(OUT) :: INDWMO(1000)
INTEGER,           INTENT(OUT) :: NFOUND

END SUBROUTINE STNINDX
END INTERFACE
END MODULE STNINDX_MOD
