MODULE STNRET_MOD
INTERFACE
SUBROUTINE STNRET(WMOLST,ICAOLST,DCNNLST,RAINLST,                    &
                  IDTYPE,POS,ISTAT,BLK,STN,ICAO,                     &
                  LAT1,LAT2,LATP,LONG1,LONG2,LONGP,HT1,HT2,          &
                  STATION,COUNTRY,REGION,DCNN,RAIN,                  &
                  OYEAR,OMONTH,ODAY,OHOUR,CYEAR,CMONTH,CDAY,CHOUR,   &
                  FLAGS,CLASS,HAW00,HAW12,MAP,RUN1,RUN2,OREC,NREC,   &
                  UA,SYN,NCM,NUM,DAY,                                &
                  SYNTIM,NCMTIM1,NCMTIM2,SQUARE,CHASER,RECNO)

IMPLICIT NONE

INTEGER,            INTENT(INOUT)    :: WMOLST(50)
CHARACTER (LEN=4),  INTENT(INOUT)    :: ICAOLST(50)
INTEGER,            INTENT(INOUT)    :: DCNNLST(50)
INTEGER,            INTENT(INOUT)    :: RAINLST(50)
INTEGER,            INTENT(INOUT)    :: IDTYPE
CHARACTER (LEN=1),  INTENT(INOUT)    :: POS
INTEGER,            INTENT(INOUT)    :: ISTAT
INTEGER,            INTENT(INOUT)    :: BLK
INTEGER,            INTENT(INOUT)    :: STN
CHARACTER (LEN=4),  INTENT(INOUT)    :: ICAO
INTEGER,            INTENT(INOUT)    :: LAT1
INTEGER,            INTENT(INOUT)    :: LAT2
CHARACTER (LEN=1),  INTENT(INOUT)    :: LATP
INTEGER,            INTENT(INOUT)    :: LONG1
INTEGER,            INTENT(INOUT)    :: LONG2
CHARACTER (LEN=1),  INTENT(INOUT)    :: LONGP
INTEGER,            INTENT(INOUT)    :: HT1
INTEGER,            INTENT(INOUT)    :: HT2
CHARACTER (LEN=42), INTENT(INOUT)    :: STATION
CHARACTER (LEN=32), INTENT(INOUT)    :: COUNTRY
INTEGER,            INTENT(INOUT)    :: REGION
INTEGER,            INTENT(INOUT)    :: DCNN
INTEGER,            INTENT(INOUT)    :: RAIN
INTEGER,            INTENT(INOUT)    :: OYEAR
INTEGER,            INTENT(INOUT)    :: OMONTH
INTEGER,            INTENT(INOUT)    :: ODAY
INTEGER,            INTENT(INOUT)    :: OHOUR
INTEGER,            INTENT(INOUT)    :: CYEAR
INTEGER,            INTENT(INOUT)    :: CMONTH
INTEGER,            INTENT(INOUT)    :: CDAY
INTEGER,            INTENT(INOUT)    :: CHOUR
CHARACTER (LEN=24), INTENT(INOUT)    :: FLAGS
INTEGER,            INTENT(INOUT)    :: CLASS
INTEGER,            INTENT(INOUT)    :: HAW00
INTEGER,            INTENT(INOUT)    :: HAW12
INTEGER,            INTENT(INOUT)    :: MAP
INTEGER,            INTENT(INOUT)    :: RUN1
INTEGER,            INTENT(INOUT)    :: RUN2
INTEGER,            INTENT(INOUT)    :: OREC
INTEGER,            INTENT(INOUT)    :: NREC
CHARACTER (LEN=4),  INTENT(INOUT)    :: UA
CHARACTER (LEN=13), INTENT(INOUT)    :: SYN
CHARACTER (LEN=23), INTENT(INOUT)    :: NCM
INTEGER,            INTENT(INOUT)    :: NUM
CHARACTER (LEN=9),  INTENT(INOUT)    :: DAY(10)
CHARACTER (LEN=24), INTENT(INOUT)    :: SYNTIM(10)
INTEGER,            INTENT(INOUT)    :: NCMTIM1(10)
INTEGER,            INTENT(INOUT)    :: NCMTIM2(10)
INTEGER,            INTENT(INOUT)    :: SQUARE
CHARACTER (LEN=6),  INTENT(INOUT)    :: CHASER
INTEGER,            INTENT(INOUT)    :: RECNO

END SUBROUTINE STNRET
END INTERFACE
END MODULE STNRET_MOD
