MODULE storchek_mod
  INTERFACE
    SUBROUTINE STORCHEK (BULL, BUL18, DATYPE, STORFLAG, MIMJ)
      IMPLICIT NONE
      CHARACTER(LEN=*), INTENT(IN)    :: BULL      ! (1)  BULLETIN TEXT
      CHARACTER(LEN=18),INTENT(IN)    :: BUL18     ! (2) 'TTAAII CCCC YYGGGG'
      CHARACTER(LEN=8), INTENT(INOUT) :: DATYPE    ! (3) DATA TYPE                                               !(GTS HEADER)
      LOGICAL,          INTENT(INOUT) :: STORFLAG  ! (4) 'STORAGE REQUIRED' FLAG
      CHARACTER(LEN=7), INTENT(OUT)   :: MIMJ!     ! (5) 'MIMIMJMJ' FROM MESS
    END SUBROUTINE STORCHEK
  END INTERFACE
END MODULE storchek_mod
