MODULE SUBPER_MOD
INTERFACE
SUBROUTINE SUBPER(ITIMST,TRANGE,INCR,ITIMND,ICMIN,RC)

IMPLICIT NONE

INTEGER,  INTENT(IN)  ::  ITIMST
INTEGER,  INTENT(IN)  ::  TRANGE
INTEGER,  INTENT(IN)  ::  INCR
INTEGER,  INTENT(IN)  ::  ITIMND
INTEGER,  INTENT(IN)  ::  ICMIN
INTEGER,  INTENT(OUT) ::  RC

END SUBROUTINE SUBPER
END INTERFACE
END MODULE SUBPER_MOD
