MODULE summary_mod
  INTERFACE
    SUBROUTINE SUMMARY (NFILES, NMSGS, KOUNTS, BULTYP, NTYPES)
    IMPLICIT NONE
    INTEGER,         INTENT(IN)    :: NTYPES             ! TOTAL NUMBER OF DATA TYPES
    INTEGER,         INTENT(IN)    :: NFILES             ! TOT NUM OF MESS PROCESSED
    INTEGER,         INTENT(IN)    :: NMSGS              ! TOT NUM OF MESS PROCESSED
    INTEGER,         INTENT(INOUT) :: KOUNTS(3,0:NTYPES) ! NUM OF MESS PROCESSED/STORED
    CHARACTER(LEN=8),INTENT(IN)    :: BULTYP(NTYPES)     ! BULLETIN TYPE CODES
    END SUBROUTINE SUMMARY
  END INTERFACE
END MODULE summary_mod
