MODULE synbul_mod
  INTERFACE
    SUBROUTINE SYNBUL(POINT,BEND,TTAAII,CCCC,YYGGGG, &
                      OCOR,CORNUM,MIMJ,NFT,BULL)

    IMPLICIT NONE

! Subroutine arguments:
    INTEGER,          INTENT(INOUT) :: POINT  !A01
    INTEGER,          INTENT(IN)    :: BEND   !A02
    CHARACTER(LEN=6), INTENT(IN)    :: TTAAII !A03
    CHARACTER(LEN=4), INTENT(IN)    :: CCCC   !A04
    CHARACTER(LEN=6), INTENT(IN)    :: YYGGGG !A05
    LOGICAL,          INTENT(IN)    :: OCOR   !A06
    CHARACTER(LEN=2), INTENT(IN)    :: CORNUM !A07  FOR WHOLE BULLETIN
    CHARACTER(LEN=*), INTENT(INOUT) :: MIMJ   !A08
    INTEGER,          INTENT(IN)    :: NFT    !A09
    CHARACTER(LEN=*), INTENT(INOUT) :: BULL   !A10

    END SUBROUTINE SYNBUL
  END INTERFACE
END MODULE synbul_mod
