MODULE synhed_mod
  INTERFACE
    SUBROUTINE SYNHED(POINT,BULEND,TTAAII,CCCC,YYGGGG, &
                      OAMD,AMDNUM,OCOR,CORNUM,MIMJ,IERR,BULL)

    IMPLICIT NONE

! Subroutine arguments:
    INTEGER,          INTENT(OUT)    :: POINT    !A01
    INTEGER,          INTENT(OUT)    :: BULEND   !A02
    CHARACTER(LEN=6), INTENT(OUT)    :: TTAAII   !A03
    CHARACTER(LEN=4), INTENT(OUT)    :: CCCC     !A04
    CHARACTER(LEN=6), INTENT(OUT)    :: YYGGGG   !A05
    LOGICAL,          INTENT(OUT)    :: OAMD     !A06
    CHARACTER(LEN=2), INTENT(OUT)    :: AMDNUM   !A07
    LOGICAL,          INTENT(OUT)    :: OCOR     !A08
    CHARACTER(LEN=2), INTENT(OUT)    :: CORNUM   !A09
    CHARACTER(LEN=*), INTENT(OUT)    :: MIMJ     !A10
    INTEGER,          INTENT(OUT)    :: IERR     !A11
    CHARACTER(LEN=*), INTENT(INOUT)  :: BULL     !A12

    END SUBROUTINE SYNHED
  END INTERFACE
END MODULE synhed_mod
