MODULE SYNIND_mod
  INTERFACE
    SUBROUTINE SYNIND(MESSAG,MESLEN,OCOR,CORNUM,TTAAII,MIMJ,  &
                      LATLON,CCCC,DATIME,NFT,BLKSIZ,SYNTAX,NELM,ID)

    IMPLICIT NONE

    CHARACTER (LEN=*), INTENT(IN)     :: MESSAG
    INTEGER, INTENT(IN)               :: MESLEN
    LOGICAL, INTENT(IN)               :: OCOR
    CHARACTER (LEN=2), INTENT(IN)     :: CORNUM
    CHARACTER (LEN=6), INTENT(IN)     :: TTAAII
    CHARACTER (LEN=4), INTENT(IN)     :: MIMJ
    REAL, INTENT(IN)                  :: LATLON(4)
    CHARACTER (LEN=4), INTENT(IN)     :: CCCC
    INTEGER, INTENT(INOUT)            :: DATIME(5)
    INTEGER, INTENT(IN)               :: NFT
    INTEGER, INTENT(IN)               :: BLKSIZ
    LOGICAL, INTENT(IN)               :: SYNTAX
    INTEGER, INTENT(IN)               :: NELM
    CHARACTER (LEN=*),INTENT(INOUT)   :: ID

    END SUBROUTINE SYNIND
  END INTERFACE
END MODULE SYNIND_mod
