MODULE SYNQC_mod
  INTERFACE
    SUBROUTINE SYNQC(REXP,WXMAN,IR,IX,N8,WPER,MSG,SYNTAX,SHIP)

    IMPLICIT NONE

    REAL, INTENT(INOUT)     :: REXP(2,*) ! (A1)
    LOGICAL, INTENT(IN)     :: WXMAN     ! (A2) TRUE IF STATION MANNED
    INTEGER, INTENT(IN)     :: IR        ! (A3)
    INTEGER, INTENT(IN)     :: IX        ! (A4)
    INTEGER, INTENT(IN)     :: N8        ! (A5)
    REAL, INTENT(IN)        :: WPER      ! (A6)
    LOGICAL, INTENT(IN)     :: MSG       ! (A7) TRUE IF QC MESSAGES ARE TO BE OUTPUT (TEST)
    LOGICAL, INTENT(OUT)    :: SYNTAX    ! (A8) TRUE IF THERE IS A SYNTAX ERROR
    LOGICAL, INTENT(IN)     :: SHIP      ! (A9) TRUE IF REPORT IS FROM A SHIP

    END SUBROUTINE SYNQC
  END INTERFACE
END MODULE SYNQC_mod
