MODULE SYNREG_mod
  INTERFACE
    SUBROUTINE SYNREG(BLOCK,STNNUM,WMOREG)

    IMPLICIT NONE

    INTEGER, INTENT(IN)  :: BLOCK    ! (A1)
    INTEGER, INTENT(IN)  :: STNNUM   ! (A2)
    INTEGER, INTENT(OUT) :: WMOREG   ! (A3)

    END SUBROUTINE SYNREG
  END INTERFACE
END MODULE SYNREG_mod
