MODULE SYNRPR_mod
  INTERFACE
    SUBROUTINE SYNRPR(HOUR,REGION,BLOCK,STNNUM,PERIOD)

    IMPLICIT NONE

    INTEGER, INTENT(IN)  :: HOUR
    INTEGER, INTENT(IN)  :: REGION
    INTEGER, INTENT(IN)  :: BLOCK    ! WMO Block number
    INTEGER, INTENT(IN)  :: STNNUM   ! Station number
    REAL, INTENT(OUT)    :: PERIOD

    END SUBROUTINE SYNRPR
  END INTERFACE
END MODULE SYNRPR_mod
