MODULE SYNSEQ_mod
  INTERFACE
    SUBROUTINE SYNSEQ(IDENT,IDATIM,PRESS,TEND,FLAG)

    IMPLICIT NONE

    CHARACTER (LEN=5), INTENT(IN)  :: IDENT
    INTEGER, INTENT(IN)            :: IDATIM(5)
    REAL, INTENT(IN)               :: PRESS
    REAL, INTENT(IN)               :: TEND
    REAL, INTENT(OUT)              :: FLAG

    END SUBROUTINE SYNSEQ
  END INTERFACE
END MODULE SYNSEQ_mod
