MODULE tafamd_mod
  INTERFACE
    SUBROUTINE TAFAMD(POINT,BEND,OAMD,AMDNUM,OCOR,CORNUM,BULL)

    IMPLICIT NONE

! Subroutine arguments:

    INTEGER,          INTENT(INOUT) ::  POINT   !A01
    INTEGER,          INTENT(INOUT) ::  BEND    !A02
    LOGICAL,          INTENT(INOUT) ::  OAMD    !A03
    CHARACTER(LEN=*), INTENT(INOUT) ::  AMDNUM  !A04
    LOGICAL,          INTENT(INOUT) ::  OCOR    !A05
    CHARACTER(LEN=*), INTENT(INOUT) ::  CORNUM  !A06
    CHARACTER(LEN=*), INTENT(INOUT) ::  BULL    !A07

    END SUBROUTINE TAFAMD
  END INTERFACE
END MODULE tafamd_mod
