MODULE tbusbul_mod
  INTERFACE
    SUBROUTINE TBUSBUL(POINT,BEND,TTAAII,YYGGGG,NFT,OERR,BULL)

    IMPLICIT NONE

    INTEGER, INTENT(INOUT)            :: POINT
    INTEGER, INTENT(INOUT)            :: BEND
    CHARACTER (LEN=6), INTENT(IN)     :: TTAAII
    CHARACTER (LEN=6), INTENT(IN)     :: YYGGGG
    INTEGER, INTENT(INOUT)            :: NFT
    LOGICAL, INTENT(OUT)              :: OERR
    CHARACTER (LEN=*), INTENT(INOUT)  :: BULL

    END SUBROUTINE TBUSBUL
  END INTERFACE
END MODULE tbusbul_mod
