MODULE tesac_mod
 INTERFACE
  SUBROUTINE TESAC(REPORT,TTAAII,CCCC,OCOR,NFT)
   CHARACTER(LEN=*),INTENT(INOUT) ::   REPORT
   CHARACTER(LEN=*),INTENT(IN)    ::   TTAAII
   CHARACTER(LEN=4),INTENT(IN)    ::   CCCC
   INTEGER,INTENT(IN)             ::   NFT
   LOGICAL,INTENT(IN)             ::   OCOR
  END SUBROUTINE TESAC
 END INTERFACE
END MODULE tesac_mod
