MODULE trange_mod
 INTERFACE
  SUBROUTINE TRANGE (VALUES, NUMOBS, NPOS, NTIME)
   INTEGER,INTENT(IN)       ::    NPOS(6)
   INTEGER,INTENT(OUT)      ::    NTIME(6,2)
   INTEGER,INTENT(IN)       ::    NUMOBS
   REAL,INTENT(IN)          ::    VALUES(NUMOBS,*)
  END SUBROUTINE TRANGE
 END INTERFACE
END MODULE trange_mod
