MODULE UAPART_mod
  INTERFACE
    SUBROUTINE UAPART(REPORT,TT,PART,PART_TYPE,STANDRD,TEMP,PILOT)

    IMPLICIT NONE

    CHARACTER (LEN=*), INTENT(IN)   :: REPORT
    CHARACTER (LEN=*), INTENT(IN)   :: TT
    CHARACTER (LEN=*), INTENT(OUT)  :: PART
    INTEGER, INTENT(OUT)            :: PART_TYPE
    LOGICAL, INTENT(OUT)            :: STANDRD
    LOGICAL, INTENT(OUT)            :: TEMP
    LOGICAL, INTENT(OUT)            :: PILOT

    END SUBROUTINE UAPART
  END INTERFACE
END MODULE UAPART_mod
