MODULE uprwinds_mod
  INTERFACE
    SUBROUTINE UPRWINDS(PROFILE,MXFINELMS,MAXLEV)

    IMPLICIT NONE

! Subroutine arguments:

    INTEGER,      INTENT(IN)    ::  MXFINELMS
    REAL,         INTENT(INOUT) ::  PROFILE(MXFINELMS)
    INTEGER,      INTENT(IN)    ::  MAXLEV

    END SUBROUTINE UPRWINDS
  END INTERFACE
END MODULE uprwinds_mod
