MODULE valout_mod
  INTERFACE
    SUBROUTINE VALOUT(STRING,IBEFOR,WIDTH,VALUE)
      IMPLICIT NONE
      CHARACTER(LEN=*), INTENT(INOUT) :: STRING
      INTEGER, INTENT(INOUT) :: IBEFOR
      INTEGER, INTENT(IN) :: WIDTH
      INTEGER, INTENT(IN) :: VALUE
    END SUBROUTINE VALOUT
  END INTERFACE
END MODULE valout_mod
