MODULE valrec_mod
  INTERFACE
    SUBROUTINE VALREC(IRECV,IFAIL,CERR)

    IMPLICIT NONE

! Subroutine arguments:

    INTEGER,      INTENT(INOUT) ::  IRECV(10)
    INTEGER,      INTENT(OUT) ::  IFAIL
    CHARACTER(*), INTENT(OUT) ::  CERR

    END SUBROUTINE VALREC
  END INTERFACE
END MODULE valrec_mod
