MODULE value_mod
  INTERFACE
    FUNCTION VALUE(STRING,IBEFOR,WIDTH) RESULT(VALUE_0)
      IMPLICIT NONE
      CHARACTER(LEN=*) :: STRING
      INTEGER :: IBEFOR
      INTEGER :: WIDTH
      INTEGER :: VALUE_0
    END FUNCTION VALUE
  END INTERFACE
END MODULE value_mod
