MODULE winpro_mod
  INTERFACE
    SUBROUTINE WINPRO(BULL,IFT)

    IMPLICIT NONE

    CHARACTER (LEN=*), INTENT(IN)  :: BULL
    INTEGER, INTENT(INOUT)         :: IFT

    END SUBROUTINE WINPRO
  END INTERFACE
END MODULE winpro_mod
