#!/bin/bash
# ----------------------------------------------------------------------------
# Function:
# To restart cylc suites that were running prior to a server reboot.
#
# For each suite listed in the "running_suites" file:
#   Do a "cylc restart" for the suite
#
# Execution:
# Place this script in ~/bin and execute it with cron with @reboot, e.g.:
# @reboot ~/bin/restart_cylc.sh >> /tmp/restart_cylc_`date "+\%Y\%m\%d"`.log 2>&1
# NB this script relies on the presence of the file containing the list of
# running suites /var/moods/.running_suites_list which is generated by the 
# script ~/bin/check_cylc.sh.
#
# Revision:
# MB-1908  Initial Version                                      Andy Moorhouse
# ----------------------------------------------------------------------------

PATH=/data/local/fcm/bin:$PATH

# Local vars...
running_suites=/var/moods/.running_suites_list

echo "`date "+%Y/%m/%d %H:%M:%S"`: $0 running... "

if [ -f $running_suites ]; then
    while read SUITE; do
        [ "${SUITE:0:1}" = "#" ] && continue  # ignore comment lines...
        echo "Restarting suite $SUITE ..."
        cylc restart $SUITE
    done < $running_suites
else
    echo "ERROR: $running_suites file not found"
fi

echo "`date "+%Y/%m/%d %H:%M:%S"`: $0 finished."
exit $rc
